export const TOPIC_LIST_COLORS = {
  primary: '#0050d4',
  primaryDim: '#0046bb',
  primaryContainer: '#7b9cff',
  secondary: '#702ae1',
  secondaryContainer: '#dcc9ff',
  tertiary: '#a23800',
  tertiaryContainer: '#ff956a',
  surface: '#f5f7f9',
  surfaceContainerLowest: '#ffffff',
  surfaceContainerLow: '#eef1f3',
  surfaceContainerHigh: '#dfe3e6',
  surfaceContainer: '#e5e9eb',
  onSurface: '#2c2f31',
  onSurfaceVariant: '#595c5e',
  onPrimary: '#f1f2ff',
  onPrimaryContainer: '#001e5a',
  onSecondary: '#f8f0ff',
  onSecondaryFixedVariant: '#6514d6',
  outlineVariant: '#abadaf',
  outline: '#747779',
};

export const TOPIC_LIST_DATA = {
  unitNumber: 'UNIT 2',
  unitTitle: 'Trees & Hierarchies',
  description: 'Mastering non-linear data structures, traversal algorithms, and self-balancing search trees for optimized data retrieval.',
  progressPercentage: 64,
  studyTimeLeft: '12h 40m',
};

export const TOPICS_DATA = [
  {
    id: 1,
    title: 'Binary Trees',
    description: 'Fundamental structures, recursion, and basic traversals (In-order, Pre-order).',
    status: 'In Progress',
    statusColor: TOPIC_LIST_COLORS.onSecondaryFixedVariant,
    statusBg: TOPIC_LIST_COLORS.secondaryContainer,
    statusDotColor: TOPIC_LIST_COLORS.secondary,
    isCompleted: false,
    isInProgress: true,
    isNotStarted: false,
  },
  {
    id: 2,
    title: 'Binary Search Trees',
    description: 'Efficient searching, insertion, and deletion logic within sorted constraints.',
    status: 'Completed',
    statusColor: TOPIC_LIST_COLORS.onSurfaceVariant,
    statusBg: TOPIC_LIST_COLORS.surfaceContainerHigh,
    statusDotColor: null,
    isCompleted: true,
    isInProgress: false,
    isNotStarted: false,
  },
  {
    id: 3,
    title: 'Red-Black Trees',
    description: 'Self-balancing properties, rotations, and strict color-based constraints.',
    status: 'Not Started',
    statusColor: TOPIC_LIST_COLORS.tertiary,
    statusBg: `${TOPIC_LIST_COLORS.tertiaryContainer}33`,
    statusDotColor: null,
    isCompleted: false,
    isInProgress: false,
    isNotStarted: true,
  },
  {
    id: 4,
    title: 'AVL Trees',
    description: 'Height-balancing factors and maintaining logarithmic time complexity.',
    status: 'Not Started',
    statusColor: TOPIC_LIST_COLORS.tertiary,
    statusBg: `${TOPIC_LIST_COLORS.tertiaryContainer}33`,
    statusDotColor: null,
    isCompleted: false,
    isInProgress: false,
    isNotStarted: true,
  },
];

export const RESOURCES_DATA = {
  video: {
    id: 1,
    type: 'Video Lecture',
    title: 'Visualizing Balances in Trees',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDEx1apwbxnq_NX3pWPq_FvMruXQSWcKVrMlZXVQahpWubonKD8kqcd2wCjYzeP2YXsTM8eGJukDsJcedrtbQanOT1_BtLZNRHBlaFrqBLef_si98-svEwcSOcU7JrblGeHVKiaZEvKptIj5bd-iPcKT6-BjIVlj7x-KvR_V8P1X8v7P50UD9K7GJ-mH4Gxu-hm59xOmypZeNMsvi8zg_oWot63sIem7mLkvKXayZyY3o51AK_9qIMksDQt-jCwJkqvHuIR7etea0g',
  },
  challenge: {
    id: 2,
    type: 'Practice Challenge',
    title: 'Test your knowledge of Red-Black Tree rotations with this interactive coding sandbox.',
    buttonText: 'Start Challenge',
  },
};
