export const QUIZ_COLORS = {
  primary: '#0050d4',
  primaryDim: '#0046bb',
  primaryContainer: '#7b9cff',
  secondary: '#702ae1',
  secondaryDim: '#6411d5',
  secondaryContainer: '#dcc9ff',
  tertiary: '#a23800',
  tertiaryDim: '#8e3000',
  tertiaryContainer: '#ff956a',
  surface: '#f5f7f9',
  surfaceContainerLowest: '#ffffff',
  surfaceContainerLow: '#eef1f3',
  surfaceContainerHigh: '#dfe3e6',
  surfaceContainer: '#e5e9eb',
  onSurface: '#2c2f31',
  onSurfaceVariant: '#595c5e',
  outlineVariant: '#abadaf',
};

export const SUBJECTS_DATA = [
  {
    id: 'math',
    title: 'Advanced Mathematics',
    quizzes: 12,
    avgScore: 88,
    icon: 'calculator',
    color: QUIZ_COLORS.primary,
    bgColor: `${QUIZ_COLORS.primary}1A`,
    accentBg: `${QUIZ_COLORS.primaryContainer}1A`,
    participants: ['JS', 'ML'],
    extraParticipants: 4,
  },
  {
    id: 'bio',
    title: 'Molecular Biology',
    quizzes: 8,
    avgScore: 74,
    icon: 'biotech',
    color: QUIZ_COLORS.secondary,
    bgColor: `${QUIZ_COLORS.secondary}1A`,
    accentBg: `${QUIZ_COLORS.secondaryContainer}33`,
    participants: ['AR', 'PH'],
    extraParticipants: 2,
  },
  {
    id: 'law',
    title: 'Constitutional Law',
    quizzes: 15,
    avgScore: 92,
    icon: 'gavel',
    color: QUIZ_COLORS.tertiary,
    bgColor: `${QUIZ_COLORS.tertiary}1A`,
    accentBg: `${QUIZ_COLORS.tertiaryContainer}33`,
    participants: ['LW', 'SK'],
    extraParticipants: 0,
  },
  {
    id: 'art',
    title: 'History of Art',
    quizzes: 5,
    avgScore: 65,
    icon: 'palette',
    color: QUIZ_COLORS.onSurfaceVariant,
    bgColor: `${QUIZ_COLORS.onSurfaceVariant}1A`,
    accentBg: `${QUIZ_COLORS.outlineVariant}1A`,
    participants: ['VD'],
    extraParticipants: 0,
    isResume: true,
  },
];

export const PERFORMANCE_DATA = {
  masteryLevel: 'Scholar Gold',
  quizzesCompleted: 142,
  progressPercent: 75,
  encouragement: 'You are in the top 5% of Law students this semester. Keep the momentum!',
  subjects: [
    { name: 'Math', score: 85, color: QUIZ_COLORS.primaryContainer },
    { name: 'Bio', score: 70, color: QUIZ_COLORS.secondaryContainer },
    { name: 'Law', score: 92, color: QUIZ_COLORS.tertiaryContainer },
    { name: 'Art', score: 60, color: QUIZ_COLORS.surfaceVariant },
    { name: 'Comp', score: 78, color: QUIZ_COLORS.primaryContainer },
  ],
};
