// Assignment page data matching assignment.html prototype

export const weeklyVelocity = {
  percentage: 84,
  trend: '+12% vs last week',
  chart: [40, 60, 35, 85, 75, 55, 90], // Bar heights for graph
};

export const subjectAllocation = {
  totalTasks: 14,
  categories: [
    { name: 'STEM', color: '#0050d4' },
    { name: 'Arts', color: '#702ae1' },
  ],
};

export const statsCards = [
  {
    id: 'due-today',
    value: '03',
    label: 'Due Today',
    icon: 'alarm',
    color: '#0050d4',
    bgColor: 'rgba(0, 80, 212, 0.1)',
  },
  {
    id: 'completed',
    value: '28',
    label: 'Completed',
    icon: 'check_circle',
    color: '#702ae1',
    bgColor: 'rgba(112, 42, 225, 0.1)',
  },
  {
    id: 'avg-grade',
    value: '3.8',
    label: 'Avg Grade',
    icon: 'star',
    color: '#a23800',
    bgColor: 'rgba(162, 56, 0, 0.1)',
  },
  {
    id: 'in-review',
    value: '12',
    label: 'In Review',
    icon: 'pending_actions',
    color: '#0050d4',
    bgColor: 'rgba(0, 80, 212, 0.1)',
  },
];

// Active Assignments (Currently in progress)
export const activeAssignments = [
  {
    id: 1,
    title: 'Multivariable Integration Project',
    subject: 'Calculus III • Dr. Aris',
    priority: 'Urgent',
    priorityColor: '#a23800',
    priorityBg: '#ffefeb',
    timeLeft: '4h left',
    files: 2,
    progress: 90,
    progressColor: '#a23800',
  },
  {
    id: 2,
    title: 'Wave-Particle Duality Essay',
    subject: 'Quantum Mechanics • Prof. Schmidt',
    priority: 'Physics',
    priorityColor: '#0050d4',
    priorityBg: 'rgba(123, 156, 255, 0.2)',
    dueDate: 'Oct 24',
    teamTask: true,
    progress: 15,
    progressColor: '#0050d4',
  },
  {
    id: 3,
    title: 'Organic Chemistry Lab Report',
    subject: 'Chemistry 301 • Dr. Chen',
    priority: 'High',
    priorityColor: '#a23800',
    priorityBg: '#ffefeb',
    timeLeft: '12h left',
    files: 3,
    progress: 65,
    progressColor: '#0050d4',
  },
  {
    id: 4,
    title: 'Machine Learning Algorithm Analysis',
    subject: 'AI & ML • Prof. Kumar',
    priority: 'Medium',
    priorityColor: '#0050d4',
    priorityBg: 'rgba(123, 156, 255, 0.2)',
    dueDate: 'Oct 26',
    progress: 45,
    progressColor: '#702ae1',
  },
];

// Upcoming Assignments (Not yet started or just released)
export const upcomingAssignments = [
  {
    id: 5,
    title: 'Renaissance Art Comparison Essay',
    subject: 'Art History',
    instructor: 'Prof. Martinez',
    priority: 'New',
    priorityColor: '#702ae1',
    priorityBg: 'rgba(112, 42, 225, 0.15)',
    dueDate: 'Oct 30',
    progress: 0,
    progressColor: '#702ae1',
    status: 'Pending',
    description: 'Compare and contrast Renaissance art techniques across different regions, focusing on the use of perspective, color theory, and religious symbolism in Italian, Northern, and Venetian schools.',
    instructions: [
      'Include at least 5 artwork examples from each region.',
      'Analyze the historical context influencing artistic choices.',
      'Provide proper citations using Chicago style format.',
    ],
    attachedFiles: [
      { id: 1, name: 'Renaissance_Art_Guide.pdf', type: 'pdf', size: '3.2 MB' },
      { id: 2, name: 'Comparison_Template.docx', type: 'doc', size: '1.1 MB' },
    ],
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAUWDs_fTv6NIxnUWWt9zN-KnSxeP4IwZSIq89nFQjTChRWNrYEwyUKQCfopZ_O1T1galtV4D_vEamGfGZKAzyTdDwlT_moEs025uLZurJSbtI8yoBnbVuWH0kMW18P6UTABs1_GRS3WMMJa_6_eH9sKVtd1vxCoSESuajUaAj5LJObD2nGbWONDQ_3gdFryy8Q377Y9o_78VGuRh4yS5dbjKNWLX7S0c8EjM8P4AJ3KJYTOWckDrfZVcIN6T3-inWGYJeNC0KA_1I',
    imageAlt: 'Renaissance art comparison visual',
  },
  {
    id: 6,
    title: 'Database Optimization Project',
    subject: 'Database Systems',
    instructor: 'Dr. Park',
    priority: 'Upcoming',
    priorityColor: '#0050d4',
    priorityBg: 'rgba(123, 156, 255, 0.2)',
    dueDate: 'Nov 02',
    teamTask: true,
    progress: 0,
    progressColor: '#0050d4',
    status: 'Pending',
    description: 'Optimize a given database schema by implementing proper indexing strategies, query optimization techniques, and normalization procedures to improve performance.',
    instructions: [
      'Work in teams of 3-4 students.',
      'Document all optimization decisions with benchmarks.',
      'Present before and after performance metrics.',
    ],
    attachedFiles: [
      { id: 1, name: 'Database_Schema.sql', type: 'sql', size: '856 KB' },
      { id: 2, name: 'Optimization_Guidelines.pdf', type: 'pdf', size: '2.1 MB' },
    ],
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAUWDs_fTv6NIxnUWWt9zN-KnSxeP4IwZSIq89nFQjTChRWNrYEwyUKQCfopZ_O1T1galtV4D_vEamGfGZKAzyTdDwlT_moEs025uLZurJSbtI8yoBnbVuWH0kMW18P6UTABs1_GRS3WMMJa_6_eH9sKVtd1vxCoSESuajUaAj5LJObD2nGbWONDQ_3gdFryy8Q377Y9o_78VGuRh4yS5dbjKNWLX7S0c8EjM8P4AJ3KJYTOWckDrfZVcIN6T3-inWGYJeNC0KA_1I',
    imageAlt: 'Database optimization visual',
  },
  {
    id: 7,
    title: 'Thermodynamics Problem Set',
    subject: 'Physics 202',
    instructor: 'Dr. Anderson',
    priority: 'Upcoming',
    priorityColor: '#0050d4',
    priorityBg: 'rgba(123, 156, 255, 0.2)',
    dueDate: 'Nov 05',
    files: 1,
    progress: 0,
    progressColor: '#0050d4',
    status: 'Pending',
    description: 'Solve advanced thermodynamics problems covering entropy, heat engines, and the laws of thermodynamics with detailed explanations.',
    instructions: [
      'Show complete derivations for all formulas used.',
      'Include unit analysis for each calculation.',
      'Graph PV diagrams where applicable.',
    ],
    attachedFiles: [
      { id: 1, name: 'Thermo_Problems.pdf', type: 'pdf', size: '1.5 MB' },
    ],
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAUWDs_fTv6NIxnUWWt9zN-KnSxeP4IwZSIq89nFQjTChRWNrYEwyUKQCfopZ_O1T1galtV4D_vEamGfGZKAzyTdDwlT_moEs025uLZurJSbtI8yoBnbVuWH0kMW18P6UTABs1_GRS3WMMJa_6_eH9sKVtd1vxCoSESuajUaAj5LJObD2nGbWONDQ_3gdFryy8Q377Y9o_78VGuRh4yS5dbjKNWLX7S0c8EjM8P4AJ3KJYTOWckDrfZVcIN6T3-inWGYJeNC0KA_1I',
    imageAlt: 'Thermodynamics visual',
  },
  {
    id: 8,
    title: 'Statistical Inference Case Study',
    subject: 'Statistics',
    instructor: 'Prof. Williams',
    priority: 'Upcoming',
    priorityColor: '#0050d4',
    priorityBg: 'rgba(123, 156, 255, 0.2)',
    dueDate: 'Nov 08',
    progress: 0,
    progressColor: '#0050d4',
    status: 'Pending',
    description: 'Analyze real-world datasets using statistical inference methods including hypothesis testing, confidence intervals, and regression analysis.',
    instructions: [
      'Use R or Python for statistical computations.',
      'Provide interpretation of p-values and confidence levels.',
      'Include visualizations of data distributions.',
    ],
    attachedFiles: [
      { id: 1, name: 'Dataset_2024.csv', type: 'csv', size: '4.3 MB' },
      { id: 2, name: 'Analysis_Template.R', type: 'code', size: '12 KB' },
    ],
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAUWDs_fTv6NIxnUWWt9zN-KnSxeP4IwZSIq89nFQjTChRWNrYEwyUKQCfopZ_O1T1galtV4D_vEamGfGZKAzyTdDwlT_moEs025uLZurJSbtI8yoBnbVuWH0kMW18P6UTABs1_GRS3WMMJa_6_eH9sKVtd1vxCoSESuajUaAj5LJObD2nGbWONDQ_3gdFryy8Q377Y9o_78VGuRh4yS5dbjKNWLX7S0c8EjM8P4AJ3KJYTOWckDrfZVcIN6T3-inWGYJeNC0KA_1I',
    imageAlt: 'Statistical analysis visual',
  },
  {
    id: 9,
    title: 'Shakespearean Literature Review',
    subject: 'English Literature',
    instructor: 'Dr. Thompson',
    priority: 'Upcoming',
    priorityColor: '#702ae1',
    priorityBg: 'rgba(112, 42, 225, 0.15)',
    dueDate: 'Nov 12',
    progress: 0,
    progressColor: '#702ae1',
    status: 'Pending',
    description: 'Write a comprehensive literature review examining critical perspectives on Shakespeare\'s use of dramatic irony and character development in Hamlet.',
    instructions: [
      'Review at least 10 scholarly sources.',
      'Synthesize different critical approaches.',
      'Develop your own thesis based on the literature.',
    ],
    attachedFiles: [
      { id: 1, name: 'Shakespeare_Bibliography.pdf', type: 'pdf', size: '890 KB' },
      { id: 2, name: 'Writing_Guide.pdf', type: 'pdf', size: '1.7 MB' },
    ],
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAUWDs_fTv6NIxnUWWt9zN-KnSxeP4IwZSIq89nFQjTChRWNrYEwyUKQCfopZ_O1T1galtV4D_vEamGfGZKAzyTdDwlT_moEs025uLZurJSbtI8yoBnbVuWH0kMW18P6UTABs1_GRS3WMMJa_6_eH9sKVtd1vxCoSESuajUaAj5LJObD2nGbWONDQ_3gdFryy8Q377Y9o_78VGuRh4yS5dbjKNWLX7S0c8EjM8P4AJ3KJYTOWckDrfZVcIN6T3-inWGYJeNC0KA_1I',
    imageAlt: 'Shakespeare literature visual',
  },
];

// Completed Assignments (Finished and graded)
export const completedAssignments = [
  {
    id: 10,
    title: 'Linear Algebra Applications',
    subject: 'Mathematics 201 • Dr. Lee',
    priority: 'Completed',
    priorityColor: '#10b981',
    priorityBg: 'rgba(16, 185, 129, 0.15)',
    dueDate: 'Oct 15',
    files: 2,
    progress: 100,
    progressColor: '#10b981',
    grade: '95%',
  },
  {
    id: 11,
    title: 'Computer Networks Security Analysis',
    subject: 'Cybersecurity • Prof. Garcia',
    priority: 'Completed',
    priorityColor: '#10b981',
    priorityBg: 'rgba(16, 185, 129, 0.15)',
    dueDate: 'Oct 12',
    progress: 100,
    progressColor: '#10b981',
    grade: '88%',
  },
  {
    id: 12,
    title: 'Environmental Impact Assessment',
    subject: 'Environmental Science • Dr. Brown',
    priority: 'Completed',
    priorityColor: '#10b981',
    priorityBg: 'rgba(16, 185, 129, 0.15)',
    dueDate: 'Oct 10',
    teamTask: true,
    progress: 100,
    progressColor: '#10b981',
    grade: '92%',
  },
  {
    id: 13,
    title: 'Classical Mechanics Problem Set',
    subject: 'Physics 101 • Prof. Newton',
    priority: 'Completed',
    priorityColor: '#10b981',
    priorityBg: 'rgba(16, 185, 129, 0.15)',
    dueDate: 'Oct 08',
    files: 1,
    progress: 100,
    progressColor: '#10b981',
    grade: '97%',
  },
  {
    id: 14,
    title: 'Data Structures Implementation',
    subject: 'Computer Science • Dr. Taylor',
    priority: 'Completed',
    priorityColor: '#10b981',
    priorityBg: 'rgba(16, 185, 129, 0.15)',
    dueDate: 'Oct 05',
    progress: 100,
    progressColor: '#10b981',
    grade: '91%',
  },
];

export const recentCompletions = [
  {
    id: 1,
    subject: 'Art History',
    grade: '98%',
    title: 'Modernism in Berlin',
    feedback: '"Excellent depth in your analysis of the Bauhaus influence. Try to expand on the socio-political context."',
    suggestion: 'Review 1920s Weimar history',
    suggestionIcon: 'lightbulb',
    borderColor: '#702ae1',
  },
  {
    id: 2,
    subject: 'Data Science',
    grade: '85%',
    title: 'Neural Network Optimizers',
    feedback: '"Strong implementation of SGD. Accuracy could be improved by tuning the learning rate decay."',
    suggestion: 'Hyperparameter Tuning',
    suggestionIcon: 'trending_up',
    borderColor: '#0050d4',
  },
];
