// Assignment page data matching assignment.html prototype

export const weeklyVelocity = {
  percentage: 84,
  trend: '+12% vs last week',
  chart: [40, 60, 35, 85, 75, 55, 90], // Bar heights for graph
};

export const subjectAllocation = {
  totalTasks: 14,
  categories: [
    { name: 'STEM', color: '#0050d4' },
    { name: 'Arts', color: '#702ae1' },
  ],
};

export const statsCards = [
  {
    id: 'due-today',
    value: '03',
    label: 'Due Today',
    icon: 'alarm',
    color: '#0050d4',
    bgColor: 'rgba(0, 80, 212, 0.1)',
  },
  {
    id: 'completed',
    value: '28',
    label: 'Completed',
    icon: 'check_circle',
    color: '#702ae1',
    bgColor: 'rgba(112, 42, 225, 0.1)',
  },
  {
    id: 'avg-grade',
    value: '3.8',
    label: 'Avg Grade',
    icon: 'star',
    color: '#a23800',
    bgColor: 'rgba(162, 56, 0, 0.1)',
  },
  {
    id: 'in-review',
    value: '12',
    label: 'In Review',
    icon: 'pending_actions',
    color: '#0050d4',
    bgColor: 'rgba(0, 80, 212, 0.1)',
  },
];

// Active Assignments (Currently in progress)
export const activeAssignments = [
  {
    id: 1,
    title: 'Multivariable Integration Project',
    subject: 'Calculus III • Dr. Aris',
    priority: 'Urgent',
    priorityColor: '#a23800',
    priorityBg: '#ffefeb',
    timeLeft: '4h left',
    files: 2,
    progress: 90,
    progressColor: '#a23800',
  },
  {
    id: 2,
    title: 'Wave-Particle Duality Essay',
    subject: 'Quantum Mechanics • Prof. Schmidt',
    priority: 'Physics',
    priorityColor: '#0050d4',
    priorityBg: 'rgba(123, 156, 255, 0.2)',
    dueDate: 'Oct 24',
    teamTask: true,
    progress: 15,
    progressColor: '#0050d4',
  },
  {
    id: 3,
    title: 'Organic Chemistry Lab Report',
    subject: 'Chemistry 301 • Dr. Chen',
    priority: 'High',
    priorityColor: '#a23800',
    priorityBg: '#ffefeb',
    timeLeft: '12h left',
    files: 3,
    progress: 65,
    progressColor: '#0050d4',
  },
  {
    id: 4,
    title: 'Machine Learning Algorithm Analysis',
    subject: 'AI & ML • Prof. Kumar',
    priority: 'Medium',
    priorityColor: '#0050d4',
    priorityBg: 'rgba(123, 156, 255, 0.2)',
    dueDate: 'Oct 26',
    progress: 45,
    progressColor: '#702ae1',
  },
];

// Upcoming Assignments (Not yet started or just released)
export const upcomingAssignments = [
  {
    id: 5,
    title: 'Renaissance Art Comparison Essay',
    subject: 'Art History • Prof. Martinez',
    priority: 'New',
    priorityColor: '#702ae1',
    priorityBg: 'rgba(112, 42, 225, 0.15)',
    dueDate: 'Oct 30',
    progress: 0,
    progressColor: '#702ae1',
  },
  {
    id: 6,
    title: 'Database Optimization Project',
    subject: 'Database Systems • Dr. Park',
    priority: 'Upcoming',
    priorityColor: '#0050d4',
    priorityBg: 'rgba(123, 156, 255, 0.2)',
    dueDate: 'Nov 02',
    teamTask: true,
    progress: 0,
    progressColor: '#0050d4',
  },
  {
    id: 7,
    title: 'Thermodynamics Problem Set',
    subject: 'Physics 202 • Dr. Anderson',
    priority: 'Upcoming',
    priorityColor: '#0050d4',
    priorityBg: 'rgba(123, 156, 255, 0.2)',
    dueDate: 'Nov 05',
    files: 1,
    progress: 0,
    progressColor: '#0050d4',
  },
  {
    id: 8,
    title: 'Statistical Inference Case Study',
    subject: 'Statistics • Prof. Williams',
    priority: 'Upcoming',
    priorityColor: '#0050d4',
    priorityBg: 'rgba(123, 156, 255, 0.2)',
    dueDate: 'Nov 08',
    progress: 0,
    progressColor: '#0050d4',
  },
  {
    id: 9,
    title: 'Shakespearean Literature Review',
    subject: 'English Literature • Dr. Thompson',
    priority: 'Upcoming',
    priorityColor: '#702ae1',
    priorityBg: 'rgba(112, 42, 225, 0.15)',
    dueDate: 'Nov 12',
    progress: 0,
    progressColor: '#702ae1',
  },
];

// Completed Assignments (Finished and graded)
export const completedAssignments = [
  {
    id: 10,
    title: 'Linear Algebra Applications',
    subject: 'Mathematics 201 • Dr. Lee',
    priority: 'Completed',
    priorityColor: '#10b981',
    priorityBg: 'rgba(16, 185, 129, 0.15)',
    dueDate: 'Oct 15',
    files: 2,
    progress: 100,
    progressColor: '#10b981',
    grade: '95%',
  },
  {
    id: 11,
    title: 'Computer Networks Security Analysis',
    subject: 'Cybersecurity • Prof. Garcia',
    priority: 'Completed',
    priorityColor: '#10b981',
    priorityBg: 'rgba(16, 185, 129, 0.15)',
    dueDate: 'Oct 12',
    progress: 100,
    progressColor: '#10b981',
    grade: '88%',
  },
  {
    id: 12,
    title: 'Environmental Impact Assessment',
    subject: 'Environmental Science • Dr. Brown',
    priority: 'Completed',
    priorityColor: '#10b981',
    priorityBg: 'rgba(16, 185, 129, 0.15)',
    dueDate: 'Oct 10',
    teamTask: true,
    progress: 100,
    progressColor: '#10b981',
    grade: '92%',
  },
  {
    id: 13,
    title: 'Classical Mechanics Problem Set',
    subject: 'Physics 101 • Prof. Newton',
    priority: 'Completed',
    priorityColor: '#10b981',
    priorityBg: 'rgba(16, 185, 129, 0.15)',
    dueDate: 'Oct 08',
    files: 1,
    progress: 100,
    progressColor: '#10b981',
    grade: '97%',
  },
  {
    id: 14,
    title: 'Data Structures Implementation',
    subject: 'Computer Science • Dr. Taylor',
    priority: 'Completed',
    priorityColor: '#10b981',
    priorityBg: 'rgba(16, 185, 129, 0.15)',
    dueDate: 'Oct 05',
    progress: 100,
    progressColor: '#10b981',
    grade: '91%',
  },
];

export const recentCompletions = [
  {
    id: 1,
    subject: 'Art History',
    grade: '98%',
    title: 'Modernism in Berlin',
    feedback: '"Excellent depth in your analysis of the Bauhaus influence. Try to expand on the socio-political context."',
    suggestion: 'Review 1920s Weimar history',
    suggestionIcon: 'lightbulb',
    borderColor: '#702ae1',
  },
  {
    id: 2,
    subject: 'Data Science',
    grade: '85%',
    title: 'Neural Network Optimizers',
    feedback: '"Strong implementation of SGD. Accuracy could be improved by tuning the learning rate decay."',
    suggestion: 'Hyperparameter Tuning',
    suggestionIcon: 'trending_up',
    borderColor: '#0050d4',
  },
];
