// Giving — the pledge → record → receipt path.
// Docs: 12-alumni-relations.md §3.4 · 05-state-machines.md §donation
//
// ─────────────────────────────────────────────────────────────
// The gap this closes
// ─────────────────────────────────────────────────────────────
// Before this, a donation could only be created by a SEED. There was no
// `POST /donations`, so an alumnus had no way to give at all: the only write was
// the office pressing "Record" on a row that already existed. The feature read as
// a ledger of money other people had arranged.
//
// ─────────────────────────────────────────────────────────────
// Why a pledge is not a receipt
// ─────────────────────────────────────────────────────────────
// The alumnus says what they gave and how. The OFFICE confirms the money landed.
// Only then is a Payment + Receipt minted. Keeping the confirmation with the
// office is what stops the receipts column from becoming self-service: a receipt
// is a tax document, and issuing one from a claim the donor typed is how a
// college ends up promising 80G deductions on money it never received.

import { prisma } from '../../../db/prisma.js';
import { conflict, forbidden, notFound, unprocessable } from '../../../lib/errors.js';
import { writeAudit } from '../../../lib/audit.js';
import { toRupees, toMinor, FUNDS, PAYMENT_METHODS, fundMeta } from './money.js';
import { isOpen } from './campaigns.service.js';
import type { Viewer } from '../directory.service.js';

/**
 * An alumnus commits to a gift. Creates the PLEDGED donation.
 *
 * The donor identity comes from the session — never from the body — otherwise any
 * alumnus could pledge money in someone else's name.
 */
export async function pledgeDonation(
  viewer: Viewer,
  body: {
    campaignId?: string | null;
    fund?: string;
    amountRupees: number;
    method?: string;
    note?: string;
    isAnonymous?: boolean;
    recurringId?: string | null;
  },
) {
  const donorProfile = await prisma.alumniProfile.findFirst({
    where: { userId: viewer.userId, institutionId: viewer.institutionId },
    select: { id: true },
  });
  // A graduate account without an alumni profile cannot be attributed to a batch
  // or appear in giving history, so the pledge is refused rather than created
  // anonymously-by-accident.
  if (!donorProfile) throw unprocessable('Complete your alumni profile before giving');

  if (body.fund && !FUNDS.includes(body.fund as never)) {
    throw unprocessable(`fund must be one of ${FUNDS.join(', ')}`);
  }
  if (body.method && !PAYMENT_METHODS.includes(body.method as never)) {
    throw unprocessable(`method must be one of ${PAYMENT_METHODS.join(', ')}`);
  }

  const amountMinor = toMinor(body.amountRupees);

  // A closed campaign must refuse the money, and must say why. Accepting a pledge
  // against a closed appeal and quietly never recording it is worse than
  // refusing it, because the donor believes they gave.
  let campaignId = body.campaignId ?? null;
  if (campaignId) {
    const campaign = await prisma.fundraisingCampaign.findFirst({
      where: { id: campaignId, institutionId: viewer.institutionId },
      select: { id: true, status: true, deadline: true, name: true },
    });
    if (!campaign) throw notFound('Campaign not found');
    if (!isOpen(campaign)) {
      throw unprocessable(`"${campaign.name}" is closed and is no longer accepting donations`);
    }
  }

  // A recurring instalment is generated by `chargeDue`, never created by hand —
  // otherwise the mandate and the donation can disagree about amount or cadence.
  if (body.recurringId) {
    throw unprocessable('A recurring instalment is created by charging the mandate, not by pledging');
  }

  // An anonymous gift still names its fund: "Anonymous, ₹50,000 to Scholarships"
  // is the whole point, and an anonymous gift with no destination is not a gift.
  const fund = body.fund ?? 'GENERAL';

  const donation = await prisma.donation.create({
    data: {
      institutionId: viewer.institutionId,
      campaignId,
      alumniUserId: viewer.userId,
      fund,
      amountMinor,
      method: body.method ?? null,
      note: body.note?.trim() || null,
      isAnonymous: body.isAnonymous === true,
      status: 'PLEDGED',
    },
    include: { campaign: { select: { name: true } } },
  });

  await writeAudit({
    actorUserId: viewer.userId,
    institutionId: viewer.institutionId,
    action: 'donation.pledge',
    entityType: 'Donation',
    entityId: donation.id,
    after: {
      amountRupees: toRupees(amountMinor),
      fund,
      campaignId,
      isAnonymous: donation.isAnonymous,
    },
  });

  return {
    id: donation.id,
    status: donation.status,
    amountRupees: toRupees(donation.amountMinor),
    fund,
    fundLabel: fundMeta(fund).label,
    campaign: donation.campaign?.name ?? null,
    isAnonymous: donation.isAnonymous,
    // Stated plainly so the donor is not left thinking they have given.
    awaitingConfirmation: true,
  };
}

/**
 * Office records the money: Payment(DONATION) + Receipt + DonationPayment link,
 * status → RECEIVED, campaign total incremented.
 *
 * Unchanged in substance from the original implementation, but moved here so the
 * write-through has one home alongside the pledge that precedes it.
 */
export async function recordDonation(
  viewer: Viewer,
  donationId: string,
  ip: string | null,
) {
  if (!viewer.isOffice) {
    throw forbidden('Only the Alumni Relations Office can confirm that money was received');
  }

  const donation = await prisma.donation.findFirst({
    where: { id: donationId, institutionId: viewer.institutionId },
    include: { alumniUser: { select: { fullName: true } } },
  });
  if (!donation) throw notFound('Donation not found');
  if (donation.status === 'RECEIVED') throw conflict('That donation is already recorded');

  // The Payment row is the authority on how the money moved. The donor's stated
  // method is carried over so the ledger and the payment agree, but a pledge made
  // with no method still records — the office knows which instrument cleared.
  const method = donation.method && PAYMENT_METHODS.includes(donation.method as never) ? donation.method : 'NET_BANKING';

  const result = await prisma.$transaction(async (tx) => {
    const count = await tx.payment.count({ where: { institutionId: viewer.institutionId } });
    const seq = String(count + 1).padStart(4, '0');
    const year = new Date().getFullYear();

    const payment = await tx.payment.create({
      data: {
        institutionId: viewer.institutionId,
        payerUserId: donation.alumniUserId,
        studentProfileId: null,
        category: 'DONATION',
        referenceNo: `PAY-${year}-${seq}`,
        amountMinor: donation.amountMinor,
        method,
        status: 'CLEARED',
        paidAt: new Date(),
        recordedByUserId: viewer.userId,
      },
    });
    const receipt = await tx.receipt.create({
      data: { paymentId: payment.id, receiptNo: `RCP-${year}-${seq}` },
    });
    await tx.donationPayment.create({ data: { paymentId: payment.id, donationId: donation.id } });
    const updated = await tx.donation.update({
      where: { id: donation.id },
      data: { status: 'RECEIVED', receivedAt: new Date(), paymentId: payment.id, method },
    });

    if (donation.campaignId) {
      await tx.fundraisingCampaign.update({
        where: { id: donation.campaignId },
        data: { raisedMinor: { increment: donation.amountMinor } },
      });
    }
    return { payment, receipt, updated };
  });

  await Promise.all([
    writeAudit({
      actorUserId: viewer.userId,
      institutionId: viewer.institutionId,
      action: 'donation.record',
      entityType: 'Donation',
      entityId: donation.id,
      before: { status: 'PLEDGED' },
      after: {
        status: 'RECEIVED',
        paymentRef: result.payment.referenceNo,
        receiptNo: result.receipt.receiptNo,
      },
      ip,
    }),
    prisma.notification.create({
      data: {
        institutionId: viewer.institutionId,
        recipientUserId: donation.alumniUserId,
        type: 'DONATION',
        title: 'Donation received — thank you!',
        body: `Your gift of ₹${toRupees(donation.amountMinor).toLocaleString('en-IN')} was recorded. Receipt ${result.receipt.receiptNo} is available to you now.`,
        sourceModule: 'alumni',
        dataJson: JSON.stringify({ module: 'alumni-donations', donationId: donation.id }),
      },
    }),
  ]);

  return {
    id: donation.id,
    status: 'RECEIVED',
    // The donor's real name is returned to the OFFICE only — this route is
    // office-gated, so it is not a leak, but the comment stops someone reusing
    // this shape in a graduate-facing endpoint later.
    donor: donation.alumniUser.fullName,
    isAnonymous: donation.isAnonymous,
    paymentReference: result.payment.referenceNo,
    receiptNo: result.receipt.receiptNo,
    amountRupees: toRupees(donation.amountMinor),
    receivedAt: result.updated.receivedAt,
  };
}
