export const REGISTRATION_COLORS = {
    primary: '#0050d4',
    primaryContainer: '#7b9cff',
    primaryFixed: '#7b9cff',
    primaryFixedDim: '#658eff',
    primaryDim: '#0046bb',
    onPrimary: '#f1f2ff',
    onPrimaryFixed: '#000000',
    onPrimaryFixedVariant: '#00266e',
    onPrimaryContainer: '#001e5a',
    secondary: '#702ae1',
    secondaryContainer: '#dcc9ff',
    secondaryFixed: '#dcc9ff',
    secondaryFixedDim: '#d0b8ff',
    secondaryDim: '#6411d5',
    onSecondary: '#f8f0ff',
    onSecondaryFixed: '#430097',
    onSecondaryFixedVariant: '#6514d6',
    onSecondaryContainer: '#5b00c7',
    tertiary: '#a23800',
    tertiaryContainer: '#ff956a',
    tertiaryFixed: '#ff956a',
    tertiaryFixedDim: '#ff7e48',
    tertiaryDim: '#8e3000',
    onTertiary: '#ffefeb',
    onTertiaryFixed: '#310b00',
    onTertiaryFixedVariant: '#692200',
    onTertiaryContainer: '#5a1c00',
    surface: '#f5f7f9',
    surfaceDim: '#d0d5d8',
    surfaceBright: '#f5f7f9',
    surfaceContainerLowest: '#ffffff',
    surfaceContainerLow: '#eef1f3',
    surfaceContainer: '#e5e9eb',
    surfaceContainerHigh: '#dfe3e6',
    surfaceContainerHighest: '#d9dde0',
    onSurface: '#2c2f31',
    onSurfaceVariant: '#595c5e',
    inverseSurface: '#0b0f10',
    inverseOnSurface: '#9a9d9f',
    inversePrimary: '#618bff',
    error: '#b31b25',
    errorContainer: '#fb5151',
    onError: '#ffefee',
    onErrorContainer: '#570008',
    background: '#f5f7f9',
    onBackground: '#2c2f31',
    outline: '#747779',
    outlineVariant: '#abadaf',
    surfaceTint: '#0050d4',
};

export const LAB_TRACKS = [
    'Neural Semantic Mapping (Track A)',
    'Recursive Syntax Models (Track B)',
    'Advanced NLP & Ethics (Track C)',
];

export const AGENDA_ITEMS = [
    {
        id: '1',
        time: '09:00 AM',
        title: 'Opening Plenary',
        description: 'Keynote: Dr. Elena Vace on Morphological Shift',
        isActive: true,
    },
    {
        id: '2',
        time: '11:30 AM',
        title: 'Deep Dive Lab',
        description: 'Hands-on semantic parsing with transformer models',
        isActive: false,
    },
    {
        id: '3',
        time: '03:00 PM',
        title: 'Research Mixer',
        description: 'Open floor for collaboration and project pitches',
        isActive: false,
    },
];

export const EVENT_PERKS = [
    {
        id: '1',
        icon: 'restaurant',
        title: 'Catered',
        description: 'Organic breakfast and networking lunch included',
        backgroundColor: REGISTRATION_COLORS.secondaryContainer,
        iconColor: REGISTRATION_COLORS.secondary,
        textColor: REGISTRATION_COLORS.onSecondaryContainer,
        descriptionColor: REGISTRATION_COLORS.secondaryDim,
    },
    {
        id: '2',
        icon: 'local-activity',
        title: 'CPD Credits',
        description: 'Earn 12 hours toward your research certification',
        backgroundColor: REGISTRATION_COLORS.tertiaryContainer,
        iconColor: REGISTRATION_COLORS.tertiary,
        textColor: REGISTRATION_COLORS.onTertiaryContainer,
        descriptionColor: REGISTRATION_COLORS.tertiaryDim,
    },
];
