export const SYLLABUS_TRACKER_COLORS = {
  primary: '#0050d4',
  primaryDim: '#0046bb',
  primaryContainer: '#7b9cff',
  secondary: '#702ae1',
  secondaryContainer: '#dcc9ff',
  tertiary: '#a23800',
  tertiaryContainer: '#ff956a',
  surface: '#f5f7f9',
  surfaceContainerLowest: '#ffffff',
  surfaceContainerLow: '#eef1f3',
  surfaceContainerHigh: '#dfe3e6',
  surfaceContainer: '#e5e9eb',
  onSurface: '#2c2f31',
  onSurfaceVariant: '#595c5e',
  outlineVariant: '#abadaf',
  onPrimary: '#f1f2ff',
};

export const ACADEMIC_DATA = {
  overallProgress: 68,
  progressLabel: 'Academic Overview',
  title: 'Your Academic Journey',
  description: "You've completed 68% of your total curriculum. Stay focused, you're ahead of the semester curve.",
};

export const SUBJECTS_DATA = [
  {
    id: 1,
    name: 'Advanced Thermodynamics',
    category: 'Mechanical Engineering',
    semester: 'SEM 04',
    type: 'CORE',
    typeColor: SYLLABUS_TRACKER_COLORS.primary,
    typeBg: `${SYLLABUS_TRACKER_COLORS.primaryContainer}1A`,
    completion: 82,
    progressColor: SYLLABUS_TRACKER_COLORS.primary,
  },
  {
    id: 2,
    name: 'Neural Architectures',
    category: 'Data Science',
    semester: 'SEM 04',
    type: 'ELECTIVE',
    typeColor: SYLLABUS_TRACKER_COLORS.secondary,
    typeBg: `${SYLLABUS_TRACKER_COLORS.secondaryContainer}1A`,
    completion: 45,
    progressColor: SYLLABUS_TRACKER_COLORS.secondary,
  },
  {
    id: 3,
    name: 'Quantum Mechanics I',
    category: 'Applied Physics',
    semester: 'SEM 04',
    type: 'LAB',
    typeColor: SYLLABUS_TRACKER_COLORS.tertiary,
    typeBg: `${SYLLABUS_TRACKER_COLORS.tertiaryContainer}1A`,
    completion: 15,
    progressColor: SYLLABUS_TRACKER_COLORS.tertiary,
  },
  {
    id: 4,
    name: 'Complex Analysis',
    category: 'Pure Mathematics',
    semester: 'SEM 03',
    type: 'CORE',
    typeColor: SYLLABUS_TRACKER_COLORS.primary,
    typeBg: `${SYLLABUS_TRACKER_COLORS.primaryContainer}1A`,
    completion: 94,
    progressColor: SYLLABUS_TRACKER_COLORS.primary,
  },
  {
    id: 5,
    name: 'Microeconomics',
    category: 'Finance',
    semester: 'SEM 04',
    type: 'GEN-ED',
    typeColor: '#64748b',
    typeBg: `${SYLLABUS_TRACKER_COLORS.surfaceContainerHigh}`,
    completion: 62,
    progressColor: '#94a3b8',
  },
];

export const MILESTONE_DATA = {
  title: 'Upcoming Milestone',
  description: 'Your mid-term portfolio review is scheduled for next Friday. Based on your current progress in "Neural Architectures", we recommend reviewing Module 3.',
  buttonText: 'Review Progress',
};
