// Color constants for Activity page
export const ACTIVITY_COLORS = {
    primary: '#0050d4',
    primaryDim: '#0046bb',
    primaryContainer: '#7b9cff',
    primaryFixed: '#7b9cff',
    primaryFixedDim: '#658eff',
    secondary: '#702ae1',
    secondaryContainer: '#dcc9ff',
    secondaryFixed: '#dcc9ff',
    secondaryFixedDim: '#d0b8ff',
    secondaryDim: '#6411d5',
    tertiary: '#a23800',
    tertiaryContainer: '#ff956a',
    tertiaryFixed: '#ff956a',
    tertiaryFixedDim: '#ff7e48',
    tertiaryDim: '#8e3000',
    surface: '#f5f7f9',
    surfaceDim: '#d0d5d8',
    surfaceBright: '#f5f7f9',
    surfaceContainerLowest: '#ffffff',
    surfaceContainerLow: '#eef1f3',
    surfaceContainer: '#e5e9eb',
    surfaceContainerHigh: '#dfe3e6',
    surfaceContainerHighest: '#d9dde0',
    onSurface: '#2c2f31',
    onSurfaceVariant: '#595c5e',
    onPrimary: '#f1f2ff',
    onSecondary: '#f8f0ff',
    onTertiary: '#ffefeb',
    background: '#f5f7f9',
    outline: '#747779',
    outlineVariant: '#abadaf',
    error: '#b31b25',
    errorContainer: '#fb5151',
    success: '#2e7d32',
    green: '#4caf50',
    greenBg: '#d1fae5',
    greenText: '#065f46',
};

// Quick look summary data
export const QUICK_LOOK = {
    totalActivities: 42,
    trend: '12% more than last week',
    focusHours: 18.5,
};

// Activity feed data
export const ACTIVITIES = [
    {
        id: 1,
        type: 'assignment',
        title: 'Advanced Macroeconomics',
        description: 'Quarterly budget analysis and projection report completed.',
        icon: 'content-paste',
        iconColor: ACTIVITY_COLORS.primary,
        iconBg: `${ACTIVITY_COLORS.primaryContainer}30`,
        status: 'Submitted',
        statusColor: ACTIVITY_COLORS.greenText,
        statusBg: ACTIVITY_COLORS.greenBg,
        timestamp: 'Today, 2:15 PM',
        hasActions: false,
    },
    {
        id: 2,
        type: 'quiz',
        title: 'Neural Networks 101',
        description: null,
        icon: 'psychology',
        iconColor: ACTIVITY_COLORS.secondary,
        iconBg: `${ACTIVITY_COLORS.secondaryContainer}30`,
        score: '94%',
        timestamp: 'Today, 10:45 AM',
        hasActions: true,
        actions: [
            { label: 'Review Results', primary: false },
            { label: 'share', icon: true, primary: true },
        ],
    },
    {
        id: 3,
        type: 'notes',
        title: 'History of Modern Architecture',
        description: '"Brutalism emerged in the 1950s, characterized by bare concrete and geometric..."',
        icon: 'menu-book',
        iconColor: ACTIVITY_COLORS.tertiary,
        iconBg: `${ACTIVITY_COLORS.tertiaryContainer}30`,
        hasImage: true,
        imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDy-A5rb2eLqWxRVkXMpceEl2PMEeSPJhL9EvjzpltGRncJp4WgdxXzr9RLbf5VPFy_sjrfbzLin9Y8dkQu_iH_xHSGkhkKKSmtx-XEanc3LwZqwTyom6iF1t26ZrBlFx8YsF3ZCW1RFbIqNIVG1ypLNwco0Noy7cNltpU5tcSKb9QJ1oaoJkqktcPatEd1hb18cn63dOidrNTb4wE2KSwqqKl_wi7SE74ZaJWQb89Pi-VLjoQx2V7xp942odmgl9_QT8mTbF0',
        timestamp: 'Yesterday, 4:20 PM',
        hasActions: false,
    },
    {
        id: 4,
        type: 'event',
        title: 'Design Workshop: Figma Prototyping',
        description: null,
        icon: 'calendar-today',
        iconColor: ACTIVITY_COLORS.onSurfaceVariant,
        iconBg: `${ACTIVITY_COLORS.onSurfaceVariant}15`,
        location: 'Building 4, Room 202',
        time: '6:00 PM',
        timestamp: null,
        hasActions: false,
        isUpcoming: true,
        borderColor: ACTIVITY_COLORS.primary,
    },
];
