export const STUDENTS = [
  {
    id: 'STU001',
    name: 'Aarav Mehta',
    rollNo: 'CSE-21-001',
    department: 'Computer Science',
    program: 'B.Tech CSE',
    semester: 'Semester 7',
    batch: 'Batch 2021',
    email: 'aarav.mehta@learnix.edu',
    phone: '+91 98765 43210',
    attendance: 92,
    cgpa: 8.4,
    status: 'Active',
    avatarColor: '#7c3aed',
  },
  {
    id: 'STU002',
    name: 'Priya Sharma',
    rollNo: 'ECE-21-014',
    department: 'Electronics',
    program: 'B.Tech ECE',
    semester: 'Semester 7',
    batch: 'Batch 2021',
    email: 'priya.sharma@learnix.edu',
    phone: '+91 98765 43211',
    attendance: 95,
    cgpa: 8.9,
    status: 'Active',
    avatarColor: '#059669',
  },
  {
    id: 'STU003',
    name: 'Rahul Verma',
    rollNo: 'MEC-22-008',
    department: 'Mechanical',
    program: 'B.Tech ME',
    semester: 'Semester 5',
    batch: 'Batch 2022',
    email: 'rahul.verma@learnix.edu',
    phone: '+91 98765 43212',
    attendance: 78,
    cgpa: 6.8,
    status: 'Active',
    avatarColor: '#d97706',
  },
  {
    id: 'STU004',
    name: 'Sneha Patel',
    rollNo: 'BBA-23-003',
    department: 'Management',
    program: 'BBA',
    semester: 'Semester 3',
    batch: 'Batch 2023',
    email: 'sneha.patel@learnix.edu',
    phone: '+91 98765 43213',
    attendance: 88,
    cgpa: 7.9,
    status: 'Active',
    avatarColor: '#dc2626',
  },
  {
    id: 'STU005',
    name: 'Vikram Singh',
    rollNo: 'CSE-22-021',
    department: 'Computer Science',
    program: 'B.Tech CSE',
    semester: 'Semester 5',
    batch: 'Batch 2022',
    email: 'vikram.singh@learnix.edu',
    phone: '+91 98765 43214',
    attendance: 65,
    cgpa: 5.9,
    status: 'Probation',
    avatarColor: '#0891b2',
  },
  {
    id: 'STU006',
    name: 'Ananya Reddy',
    rollNo: 'CSE-23-005',
    department: 'Computer Science',
    program: 'B.Tech CSE',
    semester: 'Semester 3',
    batch: 'Batch 2023',
    email: 'ananya.reddy@learnix.edu',
    phone: '+91 98765 43215',
    attendance: 97,
    cgpa: 9.1,
    status: 'Active',
    avatarColor: '#7c3aed',
  },
  {
    id: 'STU007',
    name: 'Arjun Nair',
    rollNo: 'CIV-21-011',
    department: 'Civil',
    program: 'B.Tech CE',
    semester: 'Semester 7',
    batch: 'Batch 2021',
    email: 'arjun.nair@learnix.edu',
    phone: '+91 98765 43216',
    attendance: 84,
    cgpa: 7.2,
    status: 'Active',
    avatarColor: '#059669',
  },
  {
    id: 'STU008',
    name: 'Isha Gupta',
    rollNo: 'ECE-23-019',
    department: 'Electronics',
    program: 'B.Tech ECE',
    semester: 'Semester 3',
    batch: 'Batch 2023',
    email: 'isha.gupta@learnix.edu',
    phone: '+91 98765 43217',
    attendance: 91,
    cgpa: 8.1,
    status: 'Active',
    avatarColor: '#d97706',
  },
];

export const DEPARTMENT_FILTERS = [
  { label: 'All', value: 'all' },
  { label: 'Computer Science', value: 'Computer Science' },
  { label: 'Electronics', value: 'Electronics' },
  { label: 'Mechanical', value: 'Mechanical' },
  { label: 'Management', value: 'Management' },
  { label: 'Civil', value: 'Civil' },
];

export const BATCHES = [
  { id: 'B2021', name: 'Batch 2021', students: 312, department: 'All', year: '2021-2025' },
  { id: 'B2022', name: 'Batch 2022', students: 305, department: 'All', year: '2022-2026' },
  { id: 'B2023', name: 'Batch 2023', students: 328, department: 'All', year: '2023-2027' },
  { id: 'B2024', name: 'Batch 2024', students: 289, department: 'All', year: '2024-2028' },
];

export const PENDING_APPROVALS = [
  { id: 'P1', name: 'Kabir Joshi', program: 'B.Tech CSE', appliedAt: '2 hrs ago', rollNo: 'CSE-24-001' },
  { id: 'P2', name: 'Meghna Das', program: 'BBA', appliedAt: '5 hrs ago', rollNo: 'BBA-24-002' },
  { id: 'P3', name: 'Farhan Ali', program: 'B.Tech ME', appliedAt: 'Yesterday', rollNo: 'MEC-24-003' },
];