// Mock data for lecture notes
export const mockNotes = [
  {
    id: '1',
    title: 'Calculus Fundamentals',
    author: 'Prof. Johnson',
    type: 'pdf',
    timeAgo: '2 hours ago',
    rating: 4.9,
    tags: ['derivatives', 'limits', 'integration'],
    description: 'The fundamental theorem of calculus establishes the relationship between differentiation and integration...',
    downloads: 234,
    views: 1200,
    pages: 15,
    backgroundColor: '#FEE2E2',
    iconColor: '#EF4444',
    icon: 'document-text-outline',
  },
  {
    id: '2',
    title: 'Physics Lab Report',
    author: 'Sarah M.',
    authorType: 'Student',
    type: 'ppt',
    timeAgo: '5 hours ago',
    rating: 4.2,
    tags: ['momentum', 'collision'],
    description: 'Experimental analysis of elastic and inelastic collisions in a controlled environment...',
    downloads: 89,
    views: 456,
    pages: 8,
    backgroundColor: '#FED7AA',
    iconColor: '#F97316',
    icon: 'easel-outline',
  },
  {
    id: '3',
    title: 'Chemistry Lab Notes',
    author: 'Alex K.',
    authorType: 'Student',
    type: 'scan',
    timeAgo: '1 day ago',
    rating: 4.8,
    tags: ['organic compounds', 'reactions'],
    description: 'Handwritten notes covering organic chemistry reactions and mechanisms with detailed diagrams...',
    downloads: 156,
    views: 892,
    pages: null,
    backgroundColor: '#DBEAFE',
    iconColor: '#3B82F6',
    icon: 'camera-outline',
  },
  {
    id: '4',
    title: 'AI Summary: Linear Algebra',
    author: 'AI Generated',
    type: 'ai',
    timeAgo: '1 hour ago',
    rating: null,
    tags: ['matrices', 'eigenvalues', 'vectors'],
    description: 'Key concepts: Matrix operations, determinants, and their applications in solving systems of linear equations...',
    downloads: null,
    views: null,
    readTime: '2 min read',
    backgroundColor: '#F3E8FF',
    iconColor: '#A855F7',
    icon: 'hardware-chip-outline',
  },
];

export const mockSubjects = [
  { id: 'math', name: 'Mathematics', active: true },
  { id: 'physics', name: 'Physics', active: false },
  { id: 'chemistry', name: 'Chemistry', active: false },
  { id: 'biology', name: 'Biology', active: false },
];

export const mockTabs = [
  { id: 'pdfs', name: 'PDFs', icon: 'document-text-outline', active: true },
  { id: 'ppts', name: 'PPTs', icon: 'easel-outline', active: false },
  { id: 'scans', name: 'Scans', icon: 'camera-outline', active: false },
  { id: 'ai', name: 'AI Notes', icon: 'hardware-chip-outline', active: false },
];

export const mockFilters = [
  { id: 'recent', name: 'Recent', active: true },
  { id: 'popular', name: 'Popular', active: false },
  { id: 'rating', name: 'Rating', active: false },
];
