export const DRIVE_STATS = [
  { id: 'active', label: 'Active Drives', value: '6', icon: 'briefcase', color: '#2563eb' },
  { id: 'upcoming', label: 'Upcoming', value: '4', icon: 'calendar', color: '#059669' },
  { id: 'totalApplied', label: 'Total Applied', value: '684', icon: 'people', color: '#d97706' },
  { id: 'completed', label: 'Completed', value: '12', icon: 'checkmark-done', color: '#0284c7' },
];

export const DRIVES = [
  {
    id: 'D1',
    company: 'TCS',
    role: 'Software Engineer',
    package: '₹7.5 LPA',
    date: 'Dec 10, 2026',
    mode: 'On-campus',
    eligible: 410,
    applications: 287,
    status: 'In Progress',
    stage: 'Test',
    color: '#2563eb',
  },
  {
    id: 'D2',
    company: 'Infosys',
    role: 'Systems Engineer',
    package: '₹6.8 LPA',
    date: 'Dec 14, 2026',
    mode: 'On-campus',
    eligible: 380,
    applications: 254,
    status: 'In Progress',
    stage: 'Interview',
    color: '#059669',
  },
  {
    id: 'D3',
    company: 'Wipro',
    role: 'Project Engineer',
    package: '₹5.5 LPA',
    date: 'Dec 18, 2026',
    mode: 'Virtual',
    eligible: 420,
    applications: 198,
    status: 'Registration Open',
    stage: 'Registration',
    color: '#d97706',
  },
  {
    id: 'D4',
    company: 'Deloitte',
    role: 'Analyst',
    package: '₹9.0 LPA',
    date: 'Jan 5, 2027',
    mode: 'On-campus',
    eligible: 260,
    applications: 0,
    status: 'Scheduled',
    stage: 'Not Open',
    color: '#dc2626',
  },
  {
    id: 'D5',
    company: 'Amazon',
    role: 'SDE-1',
    package: '₹21 LPA',
    date: 'Jan 12, 2027',
    mode: 'Virtual',
    eligible: 310,
    applications: 0,
    status: 'Scheduled',
    stage: 'Not Open',
    color: '#0891b2',
  },
  {
    id: 'D6',
    company: 'L&T',
    role: 'Graduate Engineer',
    package: '₹6.2 LPA',
    date: 'Dec 5, 2026',
    mode: 'On-campus',
    eligible: 350,
    applications: 145,
    status: 'Completed',
    stage: 'Offers Out',
    color: '#0ea5e9',
  },
];

export const PIPELINE_STEPS = [
  { id: 'registration', label: 'Registration', icon: 'person-add-outline', color: '#2563eb' },
  { id: 'test', label: 'Online Test', icon: 'create-outline', color: '#059669' },
  { id: 'tech', label: 'Tech Interview', icon: 'code-slash-outline', color: '#d97706' },
  { id: 'hr', label: 'HR Interview', icon: 'people-outline', color: '#0284c7' },
  { id: 'offer', label: 'Offer', icon: 'ribbon-outline', color: '#059669' },
];

export const DRIVE_APPLICANTS = [
  { id: 'AP1', name: 'Ananya Reddy', rollNo: 'CSE-23-005', branch: 'CSE', cgpa: 8.9, status: 'Shortlisted', round: 'Tech Interview', color: '#2563eb' },
  { id: 'AP2', name: 'Aarav Mehta', rollNo: 'CSE-21-001', branch: 'CSE', cgpa: 8.4, status: 'In Test', round: 'Online Test', color: '#059669' },
  { id: 'AP3', name: 'Priya Sharma', rollNo: 'ECE-21-014', branch: 'ECE', cgpa: 8.7, status: 'Shortlisted', round: 'Tech Interview', color: '#2563eb' },
  { id: 'AP4', name: 'Arjun Nair', rollNo: 'CIV-21-011', branch: 'CIVIL', cgpa: 7.9, status: 'Applied', round: 'Registration', color: '#64748b' },
  { id: 'AP5', name: 'Isha Gupta', rollNo: 'ECE-23-019', branch: 'ECE', cgpa: 8.2, status: 'Applied', round: 'Registration', color: '#64748b' },
  { id: 'AP6', name: 'Rohan Verma', rollNo: 'CSE-22-008', branch: 'CSE', cgpa: 8.1, status: 'Rejected', round: 'Test', color: '#dc2626' },
  { id: 'AP7', name: 'Sneha Kulkarni', rollNo: 'ME-21-004', branch: 'MECH', cgpa: 8.6, status: 'Shortlisted', round: 'HR Interview', color: '#0284c7' },
  { id: 'AP8', name: 'Kabir Singh', rollNo: 'BBA-22-010', branch: 'BBA', cgpa: 7.6, status: 'Applied', round: 'Registration', color: '#64748b' },
];