export const TOPIC_DIRECTORY_COLORS = {
  primary: '#0050d4',
  primaryDim: '#0046bb',
  primaryContainer: '#7b9cff',
  secondary: '#702ae1',
  secondaryDim: '#6411d5',
  secondaryContainer: '#dcc9ff',
  tertiary: '#a23800',
  tertiaryDim: '#8e3000',
  tertiaryContainer: '#ff956a',
  error: '#b31b25',
  errorContainer: '#fb5151',
  surface: '#f5f7f9',
  surfaceContainerLowest: '#ffffff',
  surfaceContainerLow: '#eef1f3',
  surfaceContainerHigh: '#dfe3e6',
  surfaceContainer: '#e5e9eb',
  onSurface: '#2c2f31',
  onSurfaceVariant: '#595c5e',
  outlineVariant: '#abadaf',
  outline: '#747779',
};

export const UNIT_DETAIL_DATA = {
  id: 'unit-02',
  title: 'Advanced Calculus',
  progress: 72,
};

export const TOPICS_DATA = [
  {
    id: 'topic-01',
    title: 'Limits & Continuity',
    icon: 'functions',
    difficulty: 'Easy',
    difficultyColor: TOPIC_DIRECTORY_COLORS.onSurfaceVariant,
    difficultyBg: TOPIC_DIRECTORY_COLORS.surfaceContainerHigh,
    highScore: 94,
    lastAttempt: '2 days ago',
    bgColor: `${TOPIC_DIRECTORY_COLORS.secondary}4D`,
    iconColor: TOPIC_DIRECTORY_COLORS.secondary,
    isReview: false,
  },
  {
    id: 'topic-02',
    title: 'Derivatives of Trig Functions',
    icon: 'architecture',
    difficulty: 'Medium',
    difficultyColor: TOPIC_DIRECTORY_COLORS.tertiary,
    difficultyBg: TOPIC_DIRECTORY_COLORS.tertiaryContainer,
    highScore: 82,
    lastAttempt: 'Today',
    bgColor: `${TOPIC_DIRECTORY_COLORS.tertiary}4D`,
    iconColor: TOPIC_DIRECTORY_COLORS.tertiary,
    isReview: false,
  },
  {
    id: 'topic-03',
    title: 'Chain Rule',
    icon: 'link',
    difficulty: 'Easy',
    difficultyColor: TOPIC_DIRECTORY_COLORS.onSurfaceVariant,
    difficultyBg: TOPIC_DIRECTORY_COLORS.surfaceContainerHigh,
    highScore: 100,
    lastAttempt: '1 week ago',
    bgColor: `${TOPIC_DIRECTORY_COLORS.primary}4D`,
    iconColor: TOPIC_DIRECTORY_COLORS.primary,
    isReview: true,
  },
  {
    id: 'topic-04',
    title: 'Implicit Differentiation',
    icon: 'visibility-off',
    difficulty: 'Hard',
    difficultyColor: TOPIC_DIRECTORY_COLORS.error,
    difficultyBg: TOPIC_DIRECTORY_COLORS.errorContainer,
    highScore: 64,
    lastAttempt: 'Yesterday',
    bgColor: `${TOPIC_DIRECTORY_COLORS.error}33`,
    iconColor: TOPIC_DIRECTORY_COLORS.error,
    isReview: false,
  },
];

export const MASTERY_INSIGHT_DATA = {
  title: 'Mastery Insight',
  recommendation: 'Based on your performance in Derivatives of Trig Functions, we recommend revisiting the fundamental identities before attempting the Implicit Differentiation quiz.',
  weakTopic: 'Derivatives of Trig Functions',
  hardTopic: 'Implicit Differentiation',
  masteryPercent: 75,
};
