// Color constants for My Registration page
export const REGISTRATION_COLORS = {
    primary: '#0050d4',
    primaryDim: '#0046bb',
    primaryContainer: '#7b9cff',
    primaryFixed: '#7b9cff',
    primaryFixedDim: '#658eff',
    secondary: '#702ae1',
    secondaryContainer: '#dcc9ff',
    secondaryFixed: '#dcc9ff',
    secondaryFixedDim: '#d0b8ff',
    secondaryDim: '#6411d5',
    tertiary: '#a23800',
    tertiaryContainer: '#ff956a',
    tertiaryFixed: '#ff956a',
    tertiaryFixedDim: '#ff7e48',
    tertiaryDim: '#8e3000',
    surface: '#f5f7f9',
    surfaceDim: '#d0d5d8',
    surfaceBright: '#f5f7f9',
    surfaceContainerLowest: '#ffffff',
    surfaceContainerLow: '#eef1f3',
    surfaceContainer: '#e5e9eb',
    surfaceContainerHigh: '#dfe3e6',
    surfaceContainerHighest: '#d9dde0',
    onSurface: '#2c2f31',
    onSurfaceVariant: '#595c5e',
    onPrimary: '#f1f2ff',
    onSecondary: '#f8f0ff',
    onTertiary: '#ffefeb',
    background: '#f5f7f9',
    outline: '#747779',
    outlineVariant: '#abadaf',
    error: '#b31b25',
    errorContainer: '#fb5151',
    emerald: '#10b981',
    emeraldBg: '#d1fae5',
    emeraldText: '#065f46',
};

// Filter options
export const FILTERS = [
    { id: 'upcoming', label: 'Upcoming', active: true },
    { id: 'past', label: 'Past', active: false },
];

// Registrations data
export const REGISTRATIONS = [
    {
        id: 1,
        title: 'The Future of Neural Interfaces',
        status: 'Checked-in',
        statusColor: REGISTRATION_COLORS.emeraldText,
        statusBg: REGISTRATION_COLORS.emeraldBg,
        statusDot: REGISTRATION_COLORS.emerald,
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCoy_-D85Xj5Du6bWu_6BR4_HXMRwIFNlklMpweFGOe6DYhj0t29zr1R_VJ6eqC5gNCE_pKa0LId5dJ0VGfm0AW4onr1RmdyVS1YS8tT3Qb5YA2Mj8TVNSbVOgW255ODPuwkMsC26X5TP9jbWuxbO7HHfuX6W9CwyciMhr95K6shI7poANxQXdYCHWsf4inxl9rnxzktYD3ANp6EtjXIuC-1JeBZ4Ap7tDEEGHucuO6Jo-7Tc6qB8g112cTJCI8gRcC_NtQgamWadQ8',
        qrCode: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCdS69C-9Xhti_OmC24BwkUvVDt-la5MxuWTBk2gnOaDZcAE077DqBbehHDDOBOT-q2h-INnoynwCvB5NeNzuahDw1-0n8pPpRgDzk6ghSMDFFvrvKc0LizudiNK6R_D_WWpuSR6mSIyQx50K11qjBj0LzZr9JoPPW1pXJ21PtZwLbyo4jzmAC0mov_m8nBAGuJqcgU7SYgc30xogQc9Ll-tFISGCCKDcxp2GCyL2T0J43gjZWvuWDS9sFZlDWOAtqU3QfXatWpe10',
        date: 'Oct 24, 2024 • 09:00 AM',
        location: 'Main Innovation Hub',
        reminder: true,
        isCompleted: false,
    },
    {
        id: 2,
        title: 'Ethics in AI: A Student Symposium',
        status: 'Not Checked-in',
        statusColor: REGISTRATION_COLORS.onSurfaceVariant,
        statusBg: REGISTRATION_COLORS.surfaceContainerHigh,
        statusDot: null,
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDEKtf_gX9IDSW74DAHdrk8lMWvfFAi7ZQoi4XcQM-3FT-sLSnC59h2ReGlxXBsKGQ_lKlpd3DlvmG4013Phm01E3CD6FmC1OwQkDvOFuJv4KMFRgDqdltDQX2F3A7sBbls0YjPUADt5or5EmoJrYnW3YAxW6bwKiB5WenvWRgi_6HWFgvLOPF2Pf_A8JaNTBhaVjMNc-LvyRX_c2CaBzpw487v9oer-uAIPuZBw9dKvIybX3RMALyjgLOQybb3jjXciOupsUXaPC8',
        qrCode: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCa52i3O-M4KGlYpR1oHUiZYlJcBvexC9HNW0bdWICZaCnfwADps3557IeiaVmj4W9hBlRkptKS-yWGLtx2GdVwkx_9LNqXIJuQF2Egffmqn11d2hmAlYYsAXTKeVPLn7EfgONfV0YKoIsDYCeAHOzbc5Ju5cKJVSErQIGTQzxK3t2zavM4VHkj6y4T1IckhL39T2I7fPod_sNPeXYo7cTfTEJgKUkEXptx-kOOwQ4K5VjifsQp4sYbEEEJGvDFumCZN4DcHUA',
        date: 'Nov 02, 2024 • 02:30 PM',
        location: 'Philosophy Hall, Rm 302',
        reminder: false,
        isCompleted: false,
    },
    {
        id: 3,
        title: 'Quantum Computing Workshop',
        status: 'Completed',
        statusColor: REGISTRATION_COLORS.onSurfaceVariant,
        statusBg: REGISTRATION_COLORS.surfaceContainer,
        statusDot: null,
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCTNd-xd1yx7hYITMpuLLl1p5Ho93EbXPYzXCeXa344NukMgxxUPIhylyOePXfLzaerwFO36ON9TYhuJE-Unjt1dTQ0prkpVuJ0s8ASyeYXxmQ8aYenldcDWL0pfwC4yYV_OgQ91AUgAVdnDKUojRTX42Xivl548QmguYDrMpCmb7cicu8V9SzN09qLBx1moChf6WJPqpAOrBruKgUZdFnKi_Ex5fGveJo8pW7m4aglW7DYMco9nVv2zsRe1cbwkU5kSKlEM2ira-w',
        qrCode: null,
        date: 'Sep 15, 2024 • 10:00 AM',
        location: 'Certificate Issued',
        reminder: false,
        isCompleted: true,
        endedText: 'Event ended 2 weeks ago',
        actionText: 'Download Materials',
        actionIcon: 'download',
    },
];
