export const UNITS = [
    {
        id: 'unit-1',
        title: 'Memory Systems & Storage',
        icon: 'neurology',
        iconBg: 'rgba(123, 156, 255, 0.1)',
        iconColor: '#0050d4',
        topicsCount: 15,
        quizzesCount: 8,
        progress: 85,
        progressColor: '#0050d4',
    },
    {
        id: 'unit-2',
        title: 'Neural Basis of Cognition',
        icon: 'psychology',
        iconBg: 'rgba(112, 42, 225, 0.1)',
        iconColor: '#702ae1',
        topicsCount: 12,
        quizzesCount: 6,
        progress: 92,
        progressColor: '#702ae1',
    },
    {
        id: 'unit-3',
        title: 'Visual Perception & Attention',
        icon: 'visibility',
        iconBg: 'rgba(162, 56, 0, 0.1)',
        iconColor: '#a23800',
        topicsCount: 18,
        quizzesCount: 10,
        progress: 74,
        progressColor: '#a23800',
    },
    {
        id: 'unit-4',
        title: 'Language Processing',
        icon: 'translate',
        iconBg: 'rgba(123, 156, 255, 0.1)',
        iconColor: '#0050d4',
        topicsCount: 14,
        quizzesCount: 7,
        progress: 80,
        progressColor: '#0050d4',
    },
    {
        id: 'unit-5',
        title: 'Judgment & Decision Making',
        icon: 'ads_click',
        iconBg: 'rgba(112, 42, 225, 0.1)',
        iconColor: '#702ae1',
        topicsCount: 20,
        quizzesCount: 12,
        progress: 89,
        progressColor: '#702ae1',
    },
];

export const HEADER = {
    breadcrumb: ['Subjects', 'Advanced Cognitive Psychology'],
    title: 'Unit Selection',
    subtitle: 'Manage course modules and monitor collective student performance for the current semester.',
};
