/**
 * Generates index.html — the root timeline.
 *
 * Mounts the 11 act sub-compositions at their absolute starts, and lays the
 * 54 narration cues and the score on the root as absolute-positioned audio.
 * Audio lives here rather than inside the acts so timing stays in one place.
 *
 * Run: node tools/build-root.mjs
 */

import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const p = (...s) => resolve(ROOT, ...s);

const acts = JSON.parse(readFileSync(p("compositions", "acts", "index.json"), "utf8")).acts;
const vo = JSON.parse(readFileSync(p("audio", "vo-manifest.json"), "utf8")).cues;

// Scene starts are read straight from the screenplay so there is exactly one
// source of truth for timing, not a copy in the manifest that could drift.
const master = readFileSync(p("docs", "MASTER-SCRIPT.md"), "utf8");
const sceneStart = new Map();
for (const m of master.matchAll(/^### (S\d+)[^\d]+?(\d+):(\d\d)[^\d]+?(\d+):(\d\d)[^\d]+?(\d+)s\s*$/gm)) {
  sceneStart.set(m[1], Number(m[2]) * 60 + Number(m[3]));
}

// Narration cues sit on the root at their scene start. A cue that bridges past
// its scene simply runs on — that is the J-cut, not an error.
const audio = vo
  .map((c) => {
    const start = sceneStart.get(c.id);
    if (start == null) throw new Error(`${c.id} has no start time in MASTER-SCRIPT.md`);
    return `    <audio id="vo-${c.id}" src="${c.file}" data-start="${start}" data-duration="${c.audioDur}"></audio>`;
  })
  .join("\n");

const actEls = acts
  .map(
    (a, i) => `    <div id="${a.compId}" class="clip"
       data-composition-id="${a.compId}"
       data-composition-src="${a.file}"
       data-start="${a.start}" data-duration="${a.dur}" data-track-index="${i % 2}"></div>`
  )
  .join("\n");

const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>Learnix Master Film</title>
<link rel="stylesheet" href="assets/tokens.css" />
<style>
  html, body { margin: 0; padding: 0; background: var(--void); }
</style>
</head>
<body>

<!--
  Learnix Master Film — root timeline
  7:00 · 1920x1080 · 30fps
  data-start / data-duration are in SECONDS.
  Generated by tools/build-root.mjs — do not hand-edit.
-->

<div id="root" data-composition-id="learnix-film" data-start="0" data-duration="420" data-width="1920" data-height="1080">

${actEls}

  <!-- score -->
  <audio id="score" src="audio/score.wav" data-start="0" data-duration="420"></audio>

  <!-- narration: absolute scene starts -->
${audio}

</div>

<script src="https://cdn.jsdelivr.net/npm/gsap@3.12.5/dist/gsap.min.js"></script>
<script>
  window.__timelines = window.__timelines || {};
  // One paused root timeline. Never add children as paused.
  window.__timelines["learnix-film"] = gsap.timeline({ paused: true });
</script>
</body>
</html>`;

writeFileSync(p("index.html"), html, "utf8");
console.log(`index.html written`);
console.log(`  ${acts.length} act compositions mounted`);
console.log(`  ${vo.length} narration cues placed`);
console.log(`  score referenced at 0s for 420s`);