export const TEACHERS = [
  {
    id: 'TCH001',
    name: 'Dr. Meera Iyer',
    department: 'Computer Science',
    designation: 'Professor',
    email: 'meera.iyer@learnix.edu',
    phone: '+91 98765 11111',
    subjects: ['Data Structures', 'Algorithms'],
    classes: 4,
    workload: 18,
    maxWorkload: 24,
    status: 'Active',
    avatarColor: '#7c3aed',
  },
  {
    id: 'TCH002',
    name: 'Prof. Rajesh Kumar',
    department: 'Electronics',
    designation: 'Associate Professor',
    email: 'rajesh.kumar@learnix.edu',
    phone: '+91 98765 11112',
    subjects: ['Digital Electronics', 'VLSI Design'],
    classes: 3,
    workload: 16,
    maxWorkload: 24,
    status: 'Active',
    avatarColor: '#059669',
  },
  {
    id: 'TCH003',
    name: 'Dr. Sunita Rao',
    department: 'Computer Science',
    designation: 'Assistant Professor',
    email: 'sunita.rao@learnix.edu',
    phone: '+91 98765 11113',
    subjects: ['DBMS', 'Computer Networks'],
    classes: 5,
    workload: 22,
    maxWorkload: 24,
    status: 'Active',
    avatarColor: '#d97706',
  },
  {
    id: 'TCH004',
    name: 'Prof. Anand Krishnan',
    department: 'Mechanical',
    designation: 'Professor',
    email: 'anand.krishnan@learnix.edu',
    phone: '+91 98765 11114',
    subjects: ['Thermodynamics', 'Fluid Mechanics'],
    classes: 3,
    workload: 14,
    maxWorkload: 24,
    status: 'On Leave',
    avatarColor: '#dc2626',
  },
  {
    id: 'TCH005',
    name: 'Dr. Kavita Desai',
    department: 'Management',
    designation: 'Professor',
    email: 'kavita.desai@learnix.edu',
    phone: '+91 98765 11115',
    subjects: ['Marketing', 'Organizational Behaviour'],
    classes: 4,
    workload: 20,
    maxWorkload: 24,
    status: 'Active',
    avatarColor: '#0891b2',
  },
  {
    id: 'TCH006',
    name: 'Prof. Mohan Das',
    department: 'Civil',
    designation: 'Assistant Professor',
    email: 'mohan.das@learnix.edu',
    phone: '+91 98765 11116',
    subjects: ['Structural Analysis', 'Surveying'],
    classes: 3,
    workload: 15,
    maxWorkload: 24,
    status: 'Active',
    avatarColor: '#7c3aed',
  },
  {
    id: 'TCH007',
    name: 'Dr. Neha Kapoor',
    department: 'Electronics',
    designation: 'Associate Professor',
    email: 'neha.kapoor@learnix.edu',
    phone: '+91 98765 11117',
    subjects: ['Signals & Systems', 'Embedded Systems'],
    classes: 4,
    workload: 19,
    maxWorkload: 24,
    status: 'Active',
    avatarColor: '#059669',
  },
  {
    id: 'TCH008',
    name: 'Prof. Sanjay Tiwari',
    department: 'Computer Science',
    designation: 'Assistant Professor',
    email: 'sanjay.tiwari@learnix.edu',
    phone: '+91 98765 11118',
    subjects: ['Python', 'Web Development'],
    classes: 5,
    workload: 23,
    maxWorkload: 24,
    status: 'Active',
    avatarColor: '#d97706',
  },
];

export const TEACHER_DEPARTMENTS = [
  { label: 'All', value: 'all' },
  { label: 'Computer Science', value: 'Computer Science' },
  { label: 'Electronics', value: 'Electronics' },
  { label: 'Mechanical', value: 'Mechanical' },
  { label: 'Management', value: 'Management' },
  { label: 'Civil', value: 'Civil' },
];

export const LEAVE_REQUESTS = [
  {
    id: 'LV001',
    teacherName: 'Prof. Anand Krishnan',
    type: 'Medical Leave',
    from: 'Oct 12, 2026',
    to: 'Oct 14, 2026',
    days: 3,
    reason: 'Scheduled surgery and recovery',
    status: 'Pending',
    avatarColor: '#dc2626',
  },
  {
    id: 'LV002',
    teacherName: 'Dr. Neha Kapoor',
    type: 'Casual Leave',
    from: 'Oct 20, 2026',
    to: 'Oct 21, 2026',
    days: 2,
    reason: 'Family function',
    status: 'Pending',
    avatarColor: '#059669',
  },
  {
    id: 'LV003',
    teacherName: 'Prof. Sanjay Tiwari',
    type: 'Earned Leave',
    from: 'Nov 2, 2026',
    to: 'Nov 6, 2026',
    days: 5,
    reason: 'Annual vacation',
    status: 'Approved',
    avatarColor: '#d97706',
  },
];