export const EVENT_DETAILS_COLORS = {
  primary: '#0050d4',
  primaryDim: '#0046bb',
  primaryContainer: '#7b9cff',
  secondary: '#702ae1',
  secondaryDim: '#6411d5',
  secondaryContainer: '#dcc9ff',
  tertiary: '#a23800',
  tertiaryDim: '#8e3000',
  tertiaryContainer: '#ff956a',
  error: '#b31b25',
  errorContainer: '#fb5151',
  surface: '#f5f7f9',
  surfaceContainerLowest: '#ffffff',
  surfaceContainerLow: '#eef1f3',
  surfaceContainer: '#e5e9eb',
  surfaceContainerHigh: '#dfe3e6',
  surfaceContainerHighest: '#d9dde0',
  onSurface: '#2c2f31',
  onSurfaceVariant: '#595c5e',
  onPrimary: '#f1f2ff',
  onSecondary: '#f8f0ff',
  onTertiary: '#ffefeb',
  onTertiaryContainer: '#5a1c00',
  outline: '#747779',
  outlineVariant: '#abadaf',
  background: '#f5f7f9',
};

export const EVENT_DETAILS_DATA = {
  title: 'Future of AI in Digital Design',
  subtitle: 'Digital Design',
  image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCy6PmL57PCUrk-lJaNsNHT2D36xZjqNfgXDTp2Y578Yaty11FVYZyDDTmcBu9_gaaauRu35-bZLo1Du_MlkQBkrkg9ff0IRC2S-n0KK58lSsHaUT-_be15sUEFmifyfA6kOgqH2hffIKG8hSC_HpUQr76MaapQRBpWVjLBjO7PlXbzYFiKZDvp7TNcC0bsdmzlvDu1XSA265k2Cz5HpTgu9OC9uEWL2SnYmo5BdD7FkQDQ_Ce8PbvbSuOV9tlSXtm9x8LzqG36sMo',
  badge: 'Limited Seats',
  about: 'Join us for an immersive workshop exploring how generative AI is reshaping the landscape of modern digital design. We\'ll dive deep into automated workflows, neural style transfer in UI, and the ethics of AI co-creation. Perfect for students looking to stay ahead of the industrial curve.',
  schedule: [
    {
      id: 1,
      time: '09:00',
      period: 'AM',
      title: 'Keynote: AI Evolution',
      location: 'Main Auditorium',
      color: 'primary',
      expanded: false,
    },
    {
      id: 2,
      time: '11:30',
      period: 'AM',
      title: 'Hands-on Prompting',
      location: 'Design Lab 4',
      color: 'secondary',
      expanded: false,
    },
    {
      id: 3,
      time: '02:00',
      period: 'PM',
      title: 'Networking Lunch',
      location: 'Central Courtyard',
      color: 'primary',
      expanded: true,
      description: 'A curated session for students to meet industry professionals. Complimentary refreshments served.',
    },
  ],
  speakers: [
    {
      id: 1,
      name: 'Elena Vance',
      role: 'Lead at Creative AI',
      specialty: 'UI/UX',
      avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCnS_nwIYKJOF61IolEnpUgY21kj79nTtM_lDP_rCnvmfRA4tZaOzXr9SIWCQly-za6P3oBiys9uBnWd0Rz_gDpBTshFSqQvWqT-bqmiX3ffiLAzoV2IHN_7_471j1ftNRcB6h6iv8DuVAsGk4gs5U19-akadyqo7sIy-T00WRjKj6AgEfn_n5-5jlB435e7mdzDqV6YeEJOMSoCyRvrX8nv6xxKnkgxY6Tm8v3YtZka_z2LXiMYipunkM__EFV_U_EU8wdJcwGQwU',
      color: 'primary',
    },
    {
      id: 2,
      name: 'Marcus Thorne',
      role: 'Systems Architect',
      specialty: 'DEV',
      avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDb2G0F9OGyIzFNUd2KOGsqmXviBcIevcI2Wgj61T0smmtsqxUuD2ErN3DX-HYx9TWsqsxjioesdijyWTDtjcZlY37gf4iGGeknz2oN7WVD0kSgqnTPQrYLa8S31osFjdnzn4jqP38zbdrtBe0o7LA8_I16YqgwR1aAAE3Iw7J0Sl1ygPHYVEuktQkO-II6OgTqf12XFX5rPee4SkDZSCORhjZjPYkKhCFKGo4iaOYfcD5QtvxOvf1tbt967nB0GMGCIuf9-q5u7X5Y',
      color: 'secondary',
    },
    {
      id: 3,
      name: 'Sarah Drasner',
      role: 'Product Strategist',
      specialty: 'STRATEGY',
      avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBPC0spHVB5KPJJLPCJcvWDcu7vhuPFIKSBfq4yOV8QSaUZNJOJ8lGJDR_drUlBF5-4p6s5KGUT4IQaDtpHO8nw2mTYVh82azAZJA_BYgxGsGfJVcYEkaTOpLdx6W0-CagJxM5URejBZ9vKFrfPw87B_YGZS2mwYSK3EIqEjs7Nady8TbZcG_dMwh7zUfxBB3OuflITVaYA3y8aCmsoExGBKmEGJSbzKckA_dnrlYvbLoIcD7TgKjJgAhODX9FQcZF9feGh9dpoDXI',
      color: 'tertiary',
    },
  ],
  location: {
    name: 'Main Innovation Hub',
    address: 'Building 4, Level 2, Tech Campus Drive, CA 94043',
    mapImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDOUG3ylstFOKPzSCpL4GIh9S46iICLyJ4oIMob9fECpYsVN8Gj7uG6gtPT9OUNcBYXWr0le5F3JnomJdeqXjuxxfFxHuLTqHrSYKAbv_q9i49PbbkxMpGxPcMygLT6PheOkcqTeXHPlKnzQHKvwnjkrsEbA37l0KKdWVOIg3YwxLsj8qWtchHsNcR9K959PhtGA41PlKe94Fi7NN9p-7-3rnULfqqp32adhsBVyOhGRBgw3X8oriD7t6A_9XIC7iT2AbPkum0Ri5g',
  },
  registrationEnds: '2h 45m',
};
