export const CONFIRMATION_COLORS = {
    primary: '#0050d4',
    primaryContainer: '#7b9cff',
    primaryFixed: '#7b9cff',
    primaryFixedDim: '#658eff',
    primaryDim: '#0046bb',
    onPrimary: '#f1f2ff',
    onPrimaryFixed: '#000000',
    onPrimaryFixedVariant: '#00266e',
    onPrimaryContainer: '#001e5a',
    secondary: '#702ae1',
    secondaryContainer: '#dcc9ff',
    secondaryFixed: '#dcc9ff',
    secondaryFixedDim: '#d0b8ff',
    secondaryDim: '#6411d5',
    onSecondary: '#f8f0ff',
    onSecondaryFixed: '#430097',
    onSecondaryFixedVariant: '#6514d6',
    onSecondaryContainer: '#5b00c7',
    tertiary: '#a23800',
    tertiaryContainer: '#ff956a',
    tertiaryFixed: '#ff956a',
    tertiaryFixedDim: '#ff7e48',
    tertiaryDim: '#8e3000',
    onTertiary: '#ffefeb',
    onTertiaryFixed: '#310b00',
    onTertiaryFixedVariant: '#692200',
    onTertiaryContainer: '#5a1c00',
    surface: '#f5f7f9',
    surfaceDim: '#d0d5d8',
    surfaceBright: '#f5f7f9',
    surfaceContainerLowest: '#ffffff',
    surfaceContainerLow: '#eef1f3',
    surfaceContainer: '#e5e9eb',
    surfaceContainerHigh: '#dfe3e6',
    surfaceContainerHighest: '#d9dde0',
    onSurface: '#2c2f31',
    onSurfaceVariant: '#595c5e',
    inverseSurface: '#0b0f10',
    inverseOnSurface: '#9a9d9f',
    inversePrimary: '#618bff',
    error: '#b31b25',
    errorContainer: '#fb5151',
    onError: '#ffefee',
    onErrorContainer: '#570008',
    background: '#f5f7f9',
    onBackground: '#2c2f31',
    outline: '#747779',
    outlineVariant: '#abadaf',
    surfaceTint: '#0050d4',
};

export const TICKET_DATA = {
    eventName: 'The Curator Summit',
    studentName: 'Alex Rivers',
    seatNumber: 'Row A, 42',
    eventDate: 'Jan 15, 2024',
    eventTime: '09:00 AM',
    ticketId: 'CUR-882-X90-QR',
    qrCode: 'https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=CUR-882-X90-QR',
};

export const NEXT_STEPS = [
    {
        id: '1',
        icon: 'forum',
        title: 'Join Discord',
        description: 'Meet your fellow students',
        backgroundColor: CONFIRMATION_COLORS.secondary + '1A',
        iconColor: CONFIRMATION_COLORS.secondary,
    },
    {
        id: '2',
        icon: 'download',
        title: 'Download Flyer',
        description: 'Syllabus & resources',
        backgroundColor: CONFIRMATION_COLORS.tertiary + '1A',
        iconColor: CONFIRMATION_COLORS.tertiary,
    },
];
