export const ACTIVE_ASSIGNMENT_COLORS = {
  primary: '#0050d4',
  primaryDim: '#0046bb',
  primaryContainer: '#7b9cff',
  secondary: '#702ae1',
  secondaryDim: '#6411d5',
  secondaryContainer: '#dcc9ff',
  tertiary: '#a23800',
  tertiaryDim: '#8e3000',
  tertiaryContainer: '#ff956a',
  error: '#b31b25',
  errorContainer: '#fb5151',
  surface: '#f5f7f9',
  surfaceContainerLowest: '#ffffff',
  surfaceContainerLow: '#eef1f3',
  surfaceContainer: '#e5e9eb',
  surfaceContainerHigh: '#dfe3e6',
  surfaceContainerHighest: '#d9dde0',
  onSurface: '#2c2f31',
  onSurfaceVariant: '#595c5e',
  onPrimary: '#f1f2ff',
  onSecondary: '#f8f0ff',
  onSecondaryContainer: '#5b00c7',
  outline: '#747779',
  outlineVariant: '#abadaf',
  background: '#f5f7f9',
};

export const ACTIVE_ASSIGNMENT_DATA = {
  id: 'UXD-402',
  code: 'UXD-402',
  title: 'Advanced UX Strategy & Competitive Research Analysis',
  priority: 'High',
  timeRemaining: '04:22:15',
  estimatedTime: 'Estimated 4h left',
  deadline: 'Oct 24, 11:59 PM',
  description: 'This assignment requires a comprehensive audit of five direct competitors in the fintech space. Focus on onboarding friction points and mental model alignment.',
  status: 'Draft Saved',
  format: 'PDF / Figma Link',
  weight: '25% of Grade',
  guidelines: [
    'Ensure all Figma links are set to "Anyone with the link can view".',
    'Append a 500-word reflection on the research methodology used.',
    'Export high-resolution assets (300dpi) for the visual audit section.',
  ],
  instructor: {
    name: 'Dr. Aris Thorne',
    title: 'Senior Design Lead',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDzq2HOl2gI22yL9yYsy2ErukBMFWccA6kgXVrHVq6eT-BEcT4jx4NY3EOMTHDx7LGmGkl3UWc6MSVR_eN2ii-lhPpB92K9_wJRXw3UUVNko6FEbJjxC1ZmtJgCEZnBGguGp-U2K1ehyh7ilYNiDzhEix0wpE_YJT_d57i2eb_onj6TMiXuUUQOV7PZXrXxc0ERRFthl70Kkzn0DuLfNVJJI3ZS4526yaSu63hKMFiuZ491HEXiHo_gYynDvSiodCHJ9jD6gPTaIlA',
  },
  resources: [
    { id: 1, name: 'Strategy_Framework.pdf', type: 'article', icon: 'article' },
    { id: 2, name: 'Heuristic_Evaluation_V2', type: 'link', icon: 'link' },
  ],
  visualAsset: {
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD_fEj2hq1PEy5iP8hOjAOI4b5JSVBC1rkqFIQh_LT_Ap7HLrdbs2YqU9sgfgeinz--ifR5jqyX2u-esQDb-iCYu0qQTs9LR8gr3K5oBoaYriHZZq3OGEt0AsffbpXhexFCe5gshBAul7T0eB8RWaQSq8CMgOU4K30XmiN6GUEcpy4H-YO5xhTUZNksonlVN13BswOze3GkIqVQGbLiRAhPfOH9WbH_15CWVSGvLbfcpdm9UUNi0sMT5mXDyg1AtZ5VvQTYtfVceOE',
    label: 'Weekly Insight',
    quote: 'Strategy is about the trade-offs you make.',
  },
};
