export const VIEW_PROFILE_COLORS = {
    primary: '#0050d4',
    primaryContainer: '#7b9cff',
    primaryFixed: '#7b9cff',
    primaryFixedDim: '#658eff',
    primaryDim: '#0046bb',
    onPrimary: '#f1f2ff',
    onPrimaryFixed: '#000000',
    onPrimaryFixedVariant: '#00266e',
    onPrimaryContainer: '#001e5a',
    secondary: '#702ae1',
    secondaryContainer: '#dcc9ff',
    secondaryFixed: '#dcc9ff',
    secondaryFixedDim: '#d0b8ff',
    secondaryDim: '#6411d5',
    onSecondary: '#f8f0ff',
    onSecondaryFixed: '#430097',
    onSecondaryFixedVariant: '#6514d6',
    onSecondaryContainer: '#5b00c7',
    tertiary: '#a23800',
    tertiaryContainer: '#ff956a',
    tertiaryFixed: '#ff956a',
    tertiaryFixedDim: '#ff7e48',
    tertiaryDim: '#8e3000',
    onTertiary: '#ffefeb',
    onTertiaryFixed: '#310b00',
    onTertiaryFixedVariant: '#692200',
    onTertiaryContainer: '#5a1c00',
    surface: '#f5f7f9',
    surfaceDim: '#d0d5d8',
    surfaceBright: '#f5f7f9',
    surfaceContainerLowest: '#ffffff',
    surfaceContainerLow: '#eef1f3',
    surfaceContainer: '#e5e9eb',
    surfaceContainerHigh: '#dfe3e6',
    surfaceContainerHighest: '#d9dde0',
    onSurface: '#2c2f31',
    onSurfaceVariant: '#595c5e',
    inverseSurface: '#0b0f10',
    inverseOnSurface: '#9a9d9f',
    inversePrimary: '#618bff',
    error: '#b31b25',
    errorContainer: '#fb5151',
    onError: '#ffefee',
    onErrorContainer: '#570008',
    background: '#f5f7f9',
    onBackground: '#2c2f31',
    outline: '#747779',
    outlineVariant: '#abadaf',
    surfaceTint: '#0050d4',
};

export const PROFILE_DATA = {
    name: 'Alex Mercer',
    role: 'Graduate Student, Architecture',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400',
    email: 'a.mercer@scholarflow.edu',
    phone: '+1 (555) 098-4321',
    bio: 'Focusing on sustainable urban environments and the integration of biophilic design in modern education centers.',
    institution: 'Design & Arts Academy',
    major: 'Architecture & Urban Planning',
    privacy: 'Public (University Network)',
};

export const PROFILE_SECTIONS = [
    {
        id: 'information',
        title: 'Information',
        items: [
            {
                id: 'name',
                label: 'Full Name',
                value: PROFILE_DATA.name,
                icon: null,
            },
            {
                id: 'email',
                label: 'Email Address',
                value: PROFILE_DATA.email,
                icon: null,
            },
            {
                id: 'phone',
                label: 'Phone Number',
                value: PROFILE_DATA.phone,
                icon: null,
            },
            {
                id: 'bio',
                label: 'Academic Bio',
                value: PROFILE_DATA.bio,
                icon: null,
                isMultiline: true,
            },
        ],
    },
    {
        id: 'academic',
        title: 'Academic Settings',
        items: [
            {
                id: 'institution',
                label: 'Institution',
                value: PROFILE_DATA.institution,
                icon: 'school',
            },
            {
                id: 'major',
                label: 'Field of Study',
                value: PROFILE_DATA.major,
                icon: 'architecture',
            },
            {
                id: 'privacy',
                label: 'Profile Visibility',
                value: PROFILE_DATA.privacy,
                icon: 'public',
            },
        ],
    },
];
