// Data constants for the student detail page - teacher view

export const DEFAULT_DETAIL = {
  email: 'student@learnix.edu',
  phone: '+91 98765 43210',
  section: 'Section A',
  enrollmentDate: 'Aug 2022',
  guardian: 'Guardian on file',
  lastLectures: ['P', 'P', 'P', 'A', 'P', 'P', 'L', 'P', 'P', 'A'],
  note: 'No notes yet.',
};

export const STUDENT_DETAILS = {
  JS: {
    email: 'julianna.sterling@learnix.edu',
    phone: '+91 98120 44512',
    section: 'Section A',
    enrollmentDate: 'Aug 2022',
    guardian: 'Rachel Sterling',
    lastLectures: ['P', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'L', 'P'],
    note: 'Consistent performer. Participates actively in class discussions.',
  },
  MK: {
    email: 'marcus.kinsley@learnix.edu',
    phone: '+91 98210 77834',
    section: 'Section A',
    enrollmentDate: 'Aug 2022',
    guardian: 'David Kinsley',
    lastLectures: ['A', 'A', 'P', 'L', 'A', 'A', 'P', 'P', 'A', 'A'],
    note: 'Missing several lectures — flagged for follow-up with counselor.',
  },
  AP: {
    email: 'ananya.patel@learnix.edu',
    phone: '+91 97654 22109',
    section: 'Section A',
    enrollmentDate: 'Aug 2022',
    guardian: 'Rohit Patel',
    lastLectures: ['P', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'P', 'P'],
    note: 'Top attendance this term.',
  },
  RC: {
    email: 'rohan.chatterjee@learnix.edu',
    phone: '+91 96543 88901',
    section: 'Section A',
    enrollmentDate: 'Aug 2022',
    guardian: 'Sunita Chatterjee',
    lastLectures: ['P', 'A', 'A', 'P', 'A', 'L', 'P', 'A', 'A', 'P'],
    note: 'Attendance below threshold. Contacted guardian this week.',
  },
  SK: {
    email: 'sofia.kapoor@learnix.edu',
    phone: '+91 99123 44567',
    section: 'Section A',
    enrollmentDate: 'Aug 2022',
    guardian: 'Arjun Kapoor',
    lastLectures: ['P', 'P', 'L', 'P', 'P', 'P', 'P', 'P', 'P', 'P'],
    note: 'Aced the last unit test.',
  },
  DL: {
    email: 'daniel.lewis@learnix.edu',
    phone: '+91 98654 11223',
    section: 'Section A',
    enrollmentDate: 'Aug 2022',
    guardian: 'Maya Lewis',
    lastLectures: ['P', 'P', 'P', 'P', 'A', 'P', 'P', 'P', 'P', 'P'],
    note: 'Prefers asynchronous material — shares good notes with peers.',
  },
  MI: {
    email: 'meera.iyer@learnix.edu',
    phone: '+91 97210 99876',
    section: 'Section A',
    enrollmentDate: 'Aug 2022',
    guardian: 'Vishal Iyer',
    lastLectures: ['P', 'L', 'P', 'L', 'P', 'P', 'L', 'P', 'P', 'L'],
    note: 'Frequently late to first-period lectures.',
  },
  TK: {
    email: 'tariq.khan@learnix.edu',
    phone: '+91 90045 33221',
    section: 'Section A',
    enrollmentDate: 'Aug 2022',
    guardian: 'Farah Khan',
    lastLectures: ['P', 'P', 'P', 'P', 'P', 'P', 'A', 'P', 'P', 'P'],
    note: 'Strong quiz scores, quiet in class.',
  },
  EM: {
    email: 'emily.marsh@learnix.edu',
    phone: '+91 98321 55667',
    section: 'Section A',
    enrollmentDate: 'Aug 2022',
    guardian: 'Peter Marsh',
    lastLectures: ['P', 'P', 'P', 'P', 'P', 'L', 'P', 'P', 'P', 'P'],
    note: '',
  },
  VS: {
    email: 'vikram.singh@learnix.edu',
    phone: '+91 97456 77889',
    section: 'Section A',
    enrollmentDate: 'Aug 2022',
    guardian: 'Neha Singh',
    lastLectures: ['P', 'P', 'A', 'P', 'P', 'P', 'P', 'A', 'P', 'P'],
    note: 'Improving steadily this month.',
  },
};

export const LECTURE_LEGEND = [
  { key: 'P', label: 'Present', color: '#16a34a' },
  { key: 'A', label: 'Absent', color: '#b31b25' },
  { key: 'L', label: 'Late', color: '#d97706' },
  { key: 'E', label: 'Excused', color: '#0050d4' },
];