// Student notifications data

export const NOTIFICATIONS_DATA = [
  {
    id: 1,
    type: 'urgent',
    icon: 'error',
    title: 'Physics Assignment Due Today',
    message: 'Submit "Quantum Mechanics Problem Set" by 11:59 PM to avoid the late penalty.',
    time: '2h ago',
    unread: true,
    bgColor: 'rgba(251, 81, 81, 0.1)',
    iconColor: '#b31b25',
  },
  {
    id: 2,
    type: 'success',
    icon: 'celebration',
    title: 'New Grade Released: Biology',
    message: 'You scored 94% in the Semester Final — top 5% of your section.',
    time: '5h ago',
    unread: true,
    bgColor: 'rgba(255, 149, 106, 0.1)',
    iconColor: '#a23800',
  },
  {
    id: 3,
    type: 'event',
    icon: 'calendar',
    title: 'Event Registration Open',
    message: 'Innovate-X 2024 Tech Symposium registration is now live. 420 slots left.',
    time: 'Yesterday',
    unread: true,
    bgColor: 'rgba(123, 156, 255, 0.1)',
    iconColor: '#0050d4',
  },
  {
    id: 4,
    type: 'info',
    icon: 'campaign',
    title: 'Campus Library Update',
    message: 'Opening hours extended to 2:00 AM for finals week.',
    time: 'Yesterday',
    unread: false,
    bgColor: 'rgba(123, 156, 255, 0.1)',
    iconColor: '#0050d4',
  },
  {
    id: 5,
    type: 'placement',
    icon: 'briefcase',
    title: 'New Placement Drive',
    message: 'Google Career Summit 2024 is accepting registrations on Oct 24.',
    time: '2 days ago',
    unread: false,
    bgColor: 'rgba(112, 42, 225, 0.1)',
    iconColor: '#702ae1',
  },
  {
    id: 6,
    type: 'info',
    icon: 'notifications',
    title: 'Attendance Alert',
    message: 'Your Cognitive Science attendance dropped below 80%. Review your record.',
    time: '3 days ago',
    unread: false,
    bgColor: 'rgba(179, 27, 37, 0.08)',
    iconColor: '#b31b25',
  },
];

export const NOTIFICATION_COLORS = {
  primary: '#0050d4',
  surface: '#f5f7f9',
  surfaceContainerLowest: '#ffffff',
  surfaceContainerLow: '#eef1f3',
  onSurface: '#2c2f31',
  onSurfaceVariant: '#595c5e',
};