// Color constants for My Applications page
export const APPLICATION_COLORS = {
    primary: '#0050d4',
    primaryDim: '#0046bb',
    primaryContainer: '#7b9cff',
    primaryFixed: '#7b9cff',
    primaryFixedDim: '#658eff',
    secondary: '#702ae1',
    secondaryContainer: '#dcc9ff',
    secondaryFixed: '#dcc9ff',
    secondaryFixedDim: '#d0b8ff',
    secondaryDim: '#6411d5',
    tertiary: '#a23800',
    tertiaryContainer: '#ff956a',
    tertiaryFixed: '#ff956a',
    tertiaryFixedDim: '#ff7e48',
    tertiaryDim: '#8e3000',
    surface: '#f5f7f9',
    surfaceDim: '#d0d5d8',
    surfaceBright: '#f5f7f9',
    surfaceContainerLowest: '#ffffff',
    surfaceContainerLow: '#eef1f3',
    surfaceContainer: '#e5e9eb',
    surfaceContainerHigh: '#dfe3e6',
    surfaceContainerHighest: '#d9dde0',
    onSurface: '#2c2f31',
    onSurfaceVariant: '#595c5e',
    onPrimary: '#f1f2ff',
    onSecondary: '#f8f0ff',
    onTertiary: '#ffefeb',
    background: '#f5f7f9',
    outline: '#747779',
    outlineVariant: '#abadaf',
    error: '#b31b25',
    errorContainer: '#fb5151',
    success: '#2e7d32',
    green: '#4caf50',
    greenBg: '#d1fae5',
    greenText: '#065f46',
    blue: '#2196f3',
    blueBg: '#bbdefb',
    blueText: '#0d47a1',
    purple: '#9c27b0',
    purpleBg: '#e1bee7',
    purpleText: '#4a148c',
    red: '#f44336',
    redBg: '#ffcdd2',
    redText: '#b71c1c',
};

// Filter options
export const FILTERS = [
    { id: 'all', label: 'All', active: true },
    { id: 'shortlisted', label: 'Shortlisted', active: false },
    { id: 'selected', label: 'Selected', active: false },
    { id: 'applied', label: 'Applied', active: false },
    { id: 'rejected', label: 'Rejected', active: false },
];

// Applications data
export const APPLICATIONS = [
    {
        id: 1,
        role: 'Senior Product Designer',
        company: 'Lumina Global Systems',
        logo: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCTemmkxUk4ApSX5uNqZWfDrScvTT7n2HVYUoYCuiU3UjRvHnUDCHwQ0VHsBPWgWKinPLuef_ozmrqbQfyXxwYuqVJPfh39Qv2raOip_twmypN6_Icr2gn4g58iNzzz1IKpmb-gq9M3kpWXjCbcpJeiBhkEMaCn7CLyDZSYPg_h1pxxrHiOzUG30CBdDI80gGD3XcLiiVxkwfFbhK43ENQExeyN7ML-ytXeqslT30OkTvthW81kjULu-v813A10nXUspteViGK6lXg',
        status: 'Selected',
        statusColor: APPLICATION_COLORS.greenText,
        statusBg: APPLICATION_COLORS.greenBg,
        date: 'Oct 24, 2024',
        isCTA: false,
    },
    {
        id: 2,
        role: 'Frontend Engineer Intern',
        company: 'Nexus Digital Lab',
        logo: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAJA41Z2HdcEnSX-qRurWZF1EBFL3S3PlP6oU23r9aaI3eOYfmOfnUb7x25tpXwywPBqXOxGQA9WLvx425yFHZuzWqPrJI6TSpvCF7tGNUOD8647OgwZ5STO08AjY5x1CHAws1s2OiRHe8LisbrwqZzZAQ2nEDNJVWNBTjqF4NCXHEeTTm6qlawxqoYkDb40Z2-kCcOFnhKR0AqypZH9N9iSAVIrYhz_6-jlrzubjP9wkf7LrKE2Lcj29n7W9MUCycbKtUdNpjXhPI',
        status: 'Shortlisted',
        statusColor: APPLICATION_COLORS.blueText,
        statusBg: APPLICATION_COLORS.blueBg,
        date: 'Oct 20, 2024',
        isCTA: false,
    },
    {
        id: 3,
        role: 'User Experience Researcher',
        company: 'Aether Creative',
        logo: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAcwGIZyYadjhtZQEtYB05rFnUck14X1eoJvERSHRC2r2Bm7FBOEc306JrSPPIDIdXC15AQw3e8PNclhKhV3bejjYiysPjp3EmOSwuXZlJQKQ2vrUWDXi02p3fKtgacuIYaC4OJkTwaiPzK_0PX3mvgN-Q2BDh1LhoRWJXQUQ8WpbOhZHOOZuwJlD6FtcZPEPIRcdBwguKnAVPQhVdXmhSF8sB9SFTOJz_y3XOBDa1g1z2mL-6i6dmgjh0Px1xkeRfJR8e3fkAGVNs',
        status: 'Applied',
        statusColor: APPLICATION_COLORS.purpleText,
        statusBg: APPLICATION_COLORS.purpleBg,
        date: 'Oct 18, 2024',
        isCTA: false,
    },
    {
        id: 4,
        role: 'Data Scientist',
        company: 'FinEdge Analytics',
        logo: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB3AH5F1VXDRgHuW9WkCZ-1P6zEjoemD9AKNDlp98GZzxCFycV2rtFVdoJjxUc1meCFL8pJBdHXBjsE2kng3HQvSyblWGWXrP2maBwXxWc1PVD-MsTYHS8m_b_nnnltu5MWDQWGnyLLezzfmPN3ZUCE-1SyV3FbYjcZtHJ-LdvW0kiJczcRNkt81_enouWRnqTdJTVV-9U0F9qpOK8R0IJ4fhh9nZdK3sMAkup6owcp1XiofiX_dJdPooxZV46TB4vOl0B5CAQ7M5Q',
        status: 'Rejected',
        statusColor: APPLICATION_COLORS.redText,
        statusBg: APPLICATION_COLORS.redBg,
        date: 'Oct 12, 2024',
        isCTA: false,
    },
    {
        id: 5,
        role: 'Content Strategist',
        company: 'EduLearn Hub',
        logo: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDIlq--zrmw0YzzFnusOmygrZReTpa-wistbm6AstE6kl5-FEubMULyYTOc-rPeDPmizHx-NmmuXPHiQrJWsXb_3_iMGdrlEQaUUtW0wCaGEXPMLpX8emlybgjLnWs_RwdZz7r4JkSgbpekqYPcPkFJfZpPDGn0bH1pUJwPnwkguQ7hnKzSE14DgA3TyiSAs0Nce8Zl1r5T8WimGll8l6NJtb48NAStzvWFONgld8XP2K1ovDo_OO2rAwEULK8Un2I6QTDmvaqyOOc',
        status: 'Applied',
        statusColor: APPLICATION_COLORS.purpleText,
        statusBg: APPLICATION_COLORS.purpleBg,
        date: 'Oct 10, 2024',
        isCTA: false,
    },
];

export const CTA_CARD = {
    title: 'Ready for more?',
    description: 'Explore 50+ new opportunities matched for your skills.',
    buttonText: 'Browse Placements',
};
