export const NOTIFICATIONS = [
  {
    id: 'n1',
    type: 'grading',
    icon: 'fact-check',
    color: '#0050d4',
    title: '12 submissions awaiting grading',
    message: 'Advanced Econometrics — Problem Set #04 has 12 new submissions, 6 past due. Tap to open the grading queue.',
    time: '2m ago',
    unread: true,
  },
  {
    id: 'n2',
    type: 'submission',
    icon: 'assignment-turned-in',
    color: '#059669',
    title: 'Alex Rivera submitted Macroeconomics Essay',
    message: 'Final draft received 2 minutes ago. The plagiarism scan completed with a 6% similarity score.',
    time: '2m ago',
    unread: true,
  },
  {
    id: 'n3',
    type: 'quiz',
    icon: 'quiz',
    color: '#702ae1',
    title: 'Quiz "Neural Networks Basics" ends in 2 days',
    message: '32 of 40 students have attempted it. Average score so far is 78%.',
    time: '1h ago',
    unread: true,
  },
  {
    id: 'n4',
    type: 'exam',
    icon: 'event',
    color: '#a23800',
    title: 'Midterm scheduled for Friday 09:00 AM',
    message: 'Hall B, Floor 2 — room booking confirmed and results publishing window opens at 2:00 PM.',
    time: '3h ago',
    unread: false,
  },
  {
    id: 'n5',
    type: 'attendance',
    icon: 'how-to-reg',
    color: '#0050d4',
    title: 'Attendance drops detected in SEC-008',
    message: '3 students in Digital Anthropology fell below 75% attendance this week. Consider a check-in.',
    time: 'Yesterday',
    unread: false,
  },
  {
    id: 'n6',
    type: 'system',
    icon: 'campaign',
    color: '#595c5e',
    title: 'Faculty meeting reminder',
    message: 'Department sync meeting at 4:00 PM in Conference Room 3. Agenda: term grading deadlines.',
    time: 'Yesterday',
    unread: false,
  },
  {
    id: 'n7',
    type: 'submission',
    icon: 'assignment-turned-in',
    color: '#059669',
    title: 'Sarah Chen submitted Statistical Modeling Project',
    message: 'Submission received 15 minutes ago with 2 attached datasets.',
    time: 'Yesterday',
    unread: false,
  },
  {
    id: 'n8',
    type: 'system',
    icon: 'verified-user',
    color: '#16a34a',
    title: 'Profile verification complete',
    message: 'Your faculty credentials were re-verified. Nothing to do.',
    time: '2 days ago',
    unread: false,
  },
];