export const TOPICS = [
    {
        id: 'topic-1',
        title: 'Perceptrons & Feedforward Models',
        icon: 'account-tree',
        iconBg: 'rgba(0, 80, 212, 0.05)',
        iconColor: '#0050d4',
        description: 'Foundational linear classifiers and the architecture of multi-layer perception systems.',
        quizzesCount: 5,
        lastUpdated: '2d ago',
        buttonVariant: 'primary',
    },
    {
        id: 'topic-2',
        title: 'Backpropagation Mechanics',
        icon: 'rebase-edit',
        iconBg: 'rgba(112, 42, 225, 0.05)',
        iconColor: '#702ae1',
        description: 'The mathematical core of gradient descent and weight optimization in deep learning.',
        quizzesCount: 5,
        lastUpdated: '2d ago',
        buttonVariant: 'primary',
    },
    {
        id: 'topic-3',
        title: 'Convolutional Layers',
        icon: 'grid-view',
        iconBg: 'rgba(162, 56, 0, 0.05)',
        iconColor: '#a23800',
        description: 'Spatial hierarchy and feature extraction through convolution and pooling mechanisms.',
        quizzesCount: 5,
        lastUpdated: '2d ago',
        buttonVariant: 'primary',
    },
    {
        id: 'topic-4',
        title: 'Recurrent Neural Networks',
        icon: 'memory',
        iconBg: 'rgba(0, 80, 212, 0.05)',
        iconColor: '#0050d4',
        description: 'Sequential data processing and the vanishing gradient problem in time-series models.',
        quizzesCount: 5,
        lastUpdated: '2d ago',
        buttonVariant: 'primary',
    },
    {
        id: 'topic-5',
        title: 'Attention Mechanisms',
        icon: 'psychology',
        iconBg: 'rgba(112, 42, 225, 0.05)',
        iconColor: '#702ae1',
        description: 'Contextual focus and the rise of Transformer architectures in cognitive modeling.',
        quizzesCount: 5,
        lastUpdated: '2d ago',
        buttonVariant: 'primary',
    },
];

export const HEADER = {
    breadcrumb: ['Subjects', 'Advanced Cognitive Psychology', 'Neural Network Architectures', 'Topics'],
    title: 'Topic Selection',
    unitTitle: 'Neural Network Architectures',
};
