export const TOPIC_COLORS = {
  primary: '#0050d4',
  primaryDim: '#0046bb',
  secondary: '#702ae1',
  tertiary: '#a23800',
  surface: '#f5f7f9',
  surfaceContainerLowest: '#ffffff',
  surfaceContainerLow: '#eef1f3',
  surfaceContainerHigh: '#dfe3e6',
  surfaceContainer: '#e5e9eb',
  onSurface: '#2c2f31',
  onSurfaceVariant: '#595c5e',
  outlineVariant: '#abadaf',
  secondaryContainer: '#dcc9ff',
  onSecondaryContainer: '#5b00c7',
  tertiaryContainer: '#ff956a',
  onTertiaryContainer: '#5a1c00',
};

export const UNIT_INFO = {
  unitNumber: 2,
  title: 'Trees & Hierarchies',
  subtitle: 'Curriculum 2024',
  description: 'Mastering non-linear data structures, from binary search trees to complex self-balancing algorithms.',
  totalTopics: 12,
  progress: 68,
};

export const TOPICS = [
  {
    id: 'topic-1',
    title: 'Introduction to Binary Trees',
    description: 'Fundamental concepts of nodes, edges, and recursive hierarchical definitions.',
    difficulty: 'Beginner',
    progress: 100,
    status: 'completed',
    difficultyColor: TOPIC_COLORS.surfaceContainerHigh,
    difficultyTextColor: TOPIC_COLORS.onSurfaceVariant,
  },
  {
    id: 'topic-2',
    title: 'AVL Tree Rotations',
    description: 'Visualizing single and double rotations for maintaining balance factors.',
    difficulty: 'Intermediate',
    progress: 0,
    status: 'not-started',
    difficultyColor: TOPIC_COLORS.secondaryContainer,
    difficultyTextColor: TOPIC_COLORS.onSecondaryContainer,
  },
  {
    id: 'topic-3',
    title: 'B-Trees & File Systems',
    description: 'Optimizing disk access through multi-way search trees and indexing.',
    difficulty: 'Advanced',
    progress: 0,
    status: 'not-started',
    difficultyColor: TOPIC_COLORS.tertiaryContainer,
    difficultyTextColor: TOPIC_COLORS.onTertiaryContainer,
  },
  {
    id: 'topic-4',
    title: 'Heap Implementations',
    description: 'Min-heaps and Max-heaps in priority queues and heapsort.',
    difficulty: 'Intermediate',
    progress: 100,
    status: 'completed',
    difficultyColor: TOPIC_COLORS.secondaryContainer,
    difficultyTextColor: TOPIC_COLORS.onSecondaryContainer,
  },
  {
    id: 'topic-5',
    title: 'Tree Traversals',
    description: 'In-order, Pre-order, and Post-order depth-first search strategies.',
    difficulty: 'Beginner',
    progress: 0,
    status: 'not-started',
    difficultyColor: TOPIC_COLORS.surfaceContainerHigh,
    difficultyTextColor: TOPIC_COLORS.onSurfaceVariant,
  },
  {
    id: 'topic-6',
    title: 'Trie Data Structures',
    description: 'Efficient prefix searching for autocomplete and dictionary applications.',
    difficulty: 'Advanced',
    progress: 100,
    status: 'completed',
    difficultyColor: TOPIC_COLORS.tertiaryContainer,
    difficultyTextColor: TOPIC_COLORS.onTertiaryContainer,
  },
];
